// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: assurance/assessment/v1/assessment.proto

package assessmentv1

import (
	v1 "github.com/ckodex-labs/ckodex-oskal/proto/assurance/common/v1"
	v11 "github.com/ckodex-labs/ckodex-oskal/proto/assurance/control/v1"
	v12 "github.com/ckodex-labs/ckodex-oskal/proto/assurance/evidence/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Claim represents a statement that a subject satisfies a control.
type Claim struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Subject       *v1.SubjectRef         `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Control       *v11.ControlRef        `protobuf:"bytes,3,opt,name=control,proto3" json:"control,omitempty"`
	TargetState   v1.AssuranceState      `protobuf:"varint,4,opt,name=target_state,json=targetState,proto3,enum=ckodex.assurance.common.v1.AssuranceState" json:"target_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Claim) Reset() {
	*x = Claim{}
	mi := &file_assurance_assessment_v1_assessment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Claim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Claim) ProtoMessage() {}

func (x *Claim) ProtoReflect() protoreflect.Message {
	mi := &file_assurance_assessment_v1_assessment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Claim.ProtoReflect.Descriptor instead.
func (*Claim) Descriptor() ([]byte, []int) {
	return file_assurance_assessment_v1_assessment_proto_rawDescGZIP(), []int{0}
}

func (x *Claim) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Claim) GetSubject() *v1.SubjectRef {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *Claim) GetControl() *v11.ControlRef {
	if x != nil {
		return x.Control
	}
	return nil
}

func (x *Claim) GetTargetState() v1.AssuranceState {
	if x != nil {
		return x.TargetState
	}
	return v1.AssuranceState(0)
}

// ClaimEvaluation is the deterministic evaluation of a Claim against verified evidence.
type ClaimEvaluation struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Id            string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Control       *v11.ControlRef           `protobuf:"bytes,2,opt,name=control,proto3" json:"control,omitempty"`
	Subject       *v1.SubjectRef            `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	State         v1.AssuranceState         `protobuf:"varint,4,opt,name=state,proto3,enum=ckodex.assurance.common.v1.AssuranceState" json:"state,omitempty"`
	Vector        *v1.AssuranceVector       `protobuf:"bytes,5,opt,name=vector,proto3" json:"vector,omitempty"`
	Epoch         *v1.AssuranceEpoch        `protobuf:"bytes,6,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Evidence      []*v12.EvidenceRef        `protobuf:"bytes,7,rep,name=evidence,proto3" json:"evidence,omitempty"`
	Completeness  *v12.EvidenceCompleteness `protobuf:"bytes,8,opt,name=completeness,proto3" json:"completeness,omitempty"`
	EvidenceRoot  string                    `protobuf:"bytes,9,opt,name=evidence_root,json=evidenceRoot,proto3" json:"evidence_root,omitempty"`
	EvaluatedAt   *timestamppb.Timestamp    `protobuf:"bytes,10,opt,name=evaluated_at,json=evaluatedAt,proto3" json:"evaluated_at,omitempty"`
	ValidUntil    *timestamppb.Timestamp    `protobuf:"bytes,11,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`
	Trace         []string                  `protobuf:"bytes,12,rep,name=trace,proto3" json:"trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimEvaluation) Reset() {
	*x = ClaimEvaluation{}
	mi := &file_assurance_assessment_v1_assessment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimEvaluation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimEvaluation) ProtoMessage() {}

func (x *ClaimEvaluation) ProtoReflect() protoreflect.Message {
	mi := &file_assurance_assessment_v1_assessment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimEvaluation.ProtoReflect.Descriptor instead.
func (*ClaimEvaluation) Descriptor() ([]byte, []int) {
	return file_assurance_assessment_v1_assessment_proto_rawDescGZIP(), []int{1}
}

func (x *ClaimEvaluation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClaimEvaluation) GetControl() *v11.ControlRef {
	if x != nil {
		return x.Control
	}
	return nil
}

func (x *ClaimEvaluation) GetSubject() *v1.SubjectRef {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *ClaimEvaluation) GetState() v1.AssuranceState {
	if x != nil {
		return x.State
	}
	return v1.AssuranceState(0)
}

func (x *ClaimEvaluation) GetVector() *v1.AssuranceVector {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *ClaimEvaluation) GetEpoch() *v1.AssuranceEpoch {
	if x != nil {
		return x.Epoch
	}
	return nil
}

func (x *ClaimEvaluation) GetEvidence() []*v12.EvidenceRef {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *ClaimEvaluation) GetCompleteness() *v12.EvidenceCompleteness {
	if x != nil {
		return x.Completeness
	}
	return nil
}

func (x *ClaimEvaluation) GetEvidenceRoot() string {
	if x != nil {
		return x.EvidenceRoot
	}
	return ""
}

func (x *ClaimEvaluation) GetEvaluatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EvaluatedAt
	}
	return nil
}

func (x *ClaimEvaluation) GetValidUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidUntil
	}
	return nil
}

func (x *ClaimEvaluation) GetTrace() []string {
	if x != nil {
		return x.Trace
	}
	return nil
}

// Finding represents a confirmed, material non-conformance.
type Finding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Subject       *v1.SubjectRef         `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Control       *v11.ControlRef        `protobuf:"bytes,3,opt,name=control,proto3" json:"control,omitempty"`
	Severity      string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	DiscoveredAt  *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=discovered_at,json=discoveredAt,proto3" json:"discovered_at,omitempty"`
	EvidenceRefs  []*v12.EvidenceRef     `protobuf:"bytes,8,rep,name=evidence_refs,json=evidenceRefs,proto3" json:"evidence_refs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Finding) Reset() {
	*x = Finding{}
	mi := &file_assurance_assessment_v1_assessment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding) ProtoMessage() {}

func (x *Finding) ProtoReflect() protoreflect.Message {
	mi := &file_assurance_assessment_v1_assessment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding.ProtoReflect.Descriptor instead.
func (*Finding) Descriptor() ([]byte, []int) {
	return file_assurance_assessment_v1_assessment_proto_rawDescGZIP(), []int{2}
}

func (x *Finding) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Finding) GetSubject() *v1.SubjectRef {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *Finding) GetControl() *v11.ControlRef {
	if x != nil {
		return x.Control
	}
	return nil
}

func (x *Finding) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Finding) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Finding) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Finding) GetDiscoveredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DiscoveredAt
	}
	return nil
}

func (x *Finding) GetEvidenceRefs() []*v12.EvidenceRef {
	if x != nil {
		return x.EvidenceRefs
	}
	return nil
}

// ControlException models an authorized, bounded derogation.
type ControlException struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Subject              *v1.SubjectRef         `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Controls             []*v11.ControlRef      `protobuf:"bytes,3,rep,name=controls,proto3" json:"controls,omitempty"`
	Justification        string                 `protobuf:"bytes,4,opt,name=justification,proto3" json:"justification,omitempty"`
	RequiredApprovers    []*v1.AuthorityRef     `protobuf:"bytes,5,rep,name=required_approvers,json=requiredApprovers,proto3" json:"required_approvers,omitempty"`
	NotBefore            *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter             *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	CompensatingControls []*v11.ControlRef      `protobuf:"bytes,8,rep,name=compensating_controls,json=compensatingControls,proto3" json:"compensating_controls,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ControlException) Reset() {
	*x = ControlException{}
	mi := &file_assurance_assessment_v1_assessment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlException) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlException) ProtoMessage() {}

func (x *ControlException) ProtoReflect() protoreflect.Message {
	mi := &file_assurance_assessment_v1_assessment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlException.ProtoReflect.Descriptor instead.
func (*ControlException) Descriptor() ([]byte, []int) {
	return file_assurance_assessment_v1_assessment_proto_rawDescGZIP(), []int{3}
}

func (x *ControlException) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ControlException) GetSubject() *v1.SubjectRef {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *ControlException) GetControls() []*v11.ControlRef {
	if x != nil {
		return x.Controls
	}
	return nil
}

func (x *ControlException) GetJustification() string {
	if x != nil {
		return x.Justification
	}
	return ""
}

func (x *ControlException) GetRequiredApprovers() []*v1.AuthorityRef {
	if x != nil {
		return x.RequiredApprovers
	}
	return nil
}

func (x *ControlException) GetNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *ControlException) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

func (x *ControlException) GetCompensatingControls() []*v11.ControlRef {
	if x != nil {
		return x.CompensatingControls
	}
	return nil
}

// AssurancePolicy specifies higher-level evaluation rules.
type AssurancePolicy struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Name                     string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RequiredState            v1.AssuranceState      `protobuf:"varint,2,opt,name=required_state,json=requiredState,proto3,enum=ckodex.assurance.common.v1.AssuranceState" json:"required_state,omitempty"`
	RequireFresh             bool                   `protobuf:"varint,3,opt,name=require_fresh,json=requireFresh,proto3" json:"require_fresh,omitempty"`
	FailOnConfirmedViolation bool                   `protobuf:"varint,4,opt,name=fail_on_confirmed_violation,json=failOnConfirmedViolation,proto3" json:"fail_on_confirmed_violation,omitempty"`
	UnknownIsViolation       bool                   `protobuf:"varint,5,opt,name=unknown_is_violation,json=unknownIsViolation,proto3" json:"unknown_is_violation,omitempty"`
	MaxEvaluationAge         *durationpb.Duration   `protobuf:"bytes,6,opt,name=max_evaluation_age,json=maxEvaluationAge,proto3" json:"max_evaluation_age,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AssurancePolicy) Reset() {
	*x = AssurancePolicy{}
	mi := &file_assurance_assessment_v1_assessment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssurancePolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssurancePolicy) ProtoMessage() {}

func (x *AssurancePolicy) ProtoReflect() protoreflect.Message {
	mi := &file_assurance_assessment_v1_assessment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssurancePolicy.ProtoReflect.Descriptor instead.
func (*AssurancePolicy) Descriptor() ([]byte, []int) {
	return file_assurance_assessment_v1_assessment_proto_rawDescGZIP(), []int{4}
}

func (x *AssurancePolicy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AssurancePolicy) GetRequiredState() v1.AssuranceState {
	if x != nil {
		return x.RequiredState
	}
	return v1.AssuranceState(0)
}

func (x *AssurancePolicy) GetRequireFresh() bool {
	if x != nil {
		return x.RequireFresh
	}
	return false
}

func (x *AssurancePolicy) GetFailOnConfirmedViolation() bool {
	if x != nil {
		return x.FailOnConfirmedViolation
	}
	return false
}

func (x *AssurancePolicy) GetUnknownIsViolation() bool {
	if x != nil {
		return x.UnknownIsViolation
	}
	return false
}

func (x *AssurancePolicy) GetMaxEvaluationAge() *durationpb.Duration {
	if x != nil {
		return x.MaxEvaluationAge
	}
	return nil
}

var File_assurance_assessment_v1_assessment_proto protoreflect.FileDescriptor

const file_assurance_assessment_v1_assessment_proto_rawDesc = "" +
	"\n" +
	"(assurance/assessment/v1/assessment.proto\x12\x1eckodex.assurance.assessment.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a assurance/common/v1/common.proto\x1a\"assurance/control/v1/control.proto\x1a$assurance/evidence/v1/evidence.proto\"\xeb\x01\n" +
	"\x05Claim\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12@\n" +
	"\asubject\x18\x02 \x01(\v2&.ckodex.assurance.common.v1.SubjectRefR\asubject\x12A\n" +
	"\acontrol\x18\x03 \x01(\v2'.ckodex.assurance.control.v1.ControlRefR\acontrol\x12M\n" +
	"\ftarget_state\x18\x04 \x01(\x0e2*.ckodex.assurance.common.v1.AssuranceStateR\vtargetState\"\xc5\x05\n" +
	"\x0fClaimEvaluation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12A\n" +
	"\acontrol\x18\x02 \x01(\v2'.ckodex.assurance.control.v1.ControlRefR\acontrol\x12@\n" +
	"\asubject\x18\x03 \x01(\v2&.ckodex.assurance.common.v1.SubjectRefR\asubject\x12@\n" +
	"\x05state\x18\x04 \x01(\x0e2*.ckodex.assurance.common.v1.AssuranceStateR\x05state\x12C\n" +
	"\x06vector\x18\x05 \x01(\v2+.ckodex.assurance.common.v1.AssuranceVectorR\x06vector\x12@\n" +
	"\x05epoch\x18\x06 \x01(\v2*.ckodex.assurance.common.v1.AssuranceEpochR\x05epoch\x12E\n" +
	"\bevidence\x18\a \x03(\v2).ckodex.assurance.evidence.v1.EvidenceRefR\bevidence\x12V\n" +
	"\fcompleteness\x18\b \x01(\v22.ckodex.assurance.evidence.v1.EvidenceCompletenessR\fcompleteness\x12#\n" +
	"\revidence_root\x18\t \x01(\tR\fevidenceRoot\x12=\n" +
	"\fevaluated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vevaluatedAt\x12;\n" +
	"\vvalid_until\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"validUntil\x12\x14\n" +
	"\x05trace\x18\f \x03(\tR\x05trace\"\x83\x03\n" +
	"\aFinding\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12@\n" +
	"\asubject\x18\x02 \x01(\v2&.ckodex.assurance.common.v1.SubjectRefR\asubject\x12A\n" +
	"\acontrol\x18\x03 \x01(\v2'.ckodex.assurance.control.v1.ControlRefR\acontrol\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12?\n" +
	"\rdiscovered_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\fdiscoveredAt\x12N\n" +
	"\revidence_refs\x18\b \x03(\v2).ckodex.assurance.evidence.v1.EvidenceRefR\fevidenceRefs\"\xfa\x03\n" +
	"\x10ControlException\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12@\n" +
	"\asubject\x18\x02 \x01(\v2&.ckodex.assurance.common.v1.SubjectRefR\asubject\x12C\n" +
	"\bcontrols\x18\x03 \x03(\v2'.ckodex.assurance.control.v1.ControlRefR\bcontrols\x12$\n" +
	"\rjustification\x18\x04 \x01(\tR\rjustification\x12W\n" +
	"\x12required_approvers\x18\x05 \x03(\v2(.ckodex.assurance.common.v1.AuthorityRefR\x11requiredApprovers\x129\n" +
	"\n" +
	"not_before\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tnotBefore\x127\n" +
	"\tnot_after\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\x12\\\n" +
	"\x15compensating_controls\x18\b \x03(\v2'.ckodex.assurance.control.v1.ControlRefR\x14compensatingControls\"\xd7\x02\n" +
	"\x0fAssurancePolicy\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12Q\n" +
	"\x0erequired_state\x18\x02 \x01(\x0e2*.ckodex.assurance.common.v1.AssuranceStateR\rrequiredState\x12#\n" +
	"\rrequire_fresh\x18\x03 \x01(\bR\frequireFresh\x12=\n" +
	"\x1bfail_on_confirmed_violation\x18\x04 \x01(\bR\x18failOnConfirmedViolation\x120\n" +
	"\x14unknown_is_violation\x18\x05 \x01(\bR\x12unknownIsViolation\x12G\n" +
	"\x12max_evaluation_age\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\x10maxEvaluationAgeBPZNgithub.com/ckodex-labs/ckodex-oskal/proto/assurance/assessment/v1;assessmentv1b\x06proto3"

var (
	file_assurance_assessment_v1_assessment_proto_rawDescOnce sync.Once
	file_assurance_assessment_v1_assessment_proto_rawDescData []byte
)

func file_assurance_assessment_v1_assessment_proto_rawDescGZIP() []byte {
	file_assurance_assessment_v1_assessment_proto_rawDescOnce.Do(func() {
		file_assurance_assessment_v1_assessment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_assurance_assessment_v1_assessment_proto_rawDesc), len(file_assurance_assessment_v1_assessment_proto_rawDesc)))
	})
	return file_assurance_assessment_v1_assessment_proto_rawDescData
}

var file_assurance_assessment_v1_assessment_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_assurance_assessment_v1_assessment_proto_goTypes = []any{
	(*Claim)(nil),                    // 0: ckodex.assurance.assessment.v1.Claim
	(*ClaimEvaluation)(nil),          // 1: ckodex.assurance.assessment.v1.ClaimEvaluation
	(*Finding)(nil),                  // 2: ckodex.assurance.assessment.v1.Finding
	(*ControlException)(nil),         // 3: ckodex.assurance.assessment.v1.ControlException
	(*AssurancePolicy)(nil),          // 4: ckodex.assurance.assessment.v1.AssurancePolicy
	(*v1.SubjectRef)(nil),            // 5: ckodex.assurance.common.v1.SubjectRef
	(*v11.ControlRef)(nil),           // 6: ckodex.assurance.control.v1.ControlRef
	(v1.AssuranceState)(0),           // 7: ckodex.assurance.common.v1.AssuranceState
	(*v1.AssuranceVector)(nil),       // 8: ckodex.assurance.common.v1.AssuranceVector
	(*v1.AssuranceEpoch)(nil),        // 9: ckodex.assurance.common.v1.AssuranceEpoch
	(*v12.EvidenceRef)(nil),          // 10: ckodex.assurance.evidence.v1.EvidenceRef
	(*v12.EvidenceCompleteness)(nil), // 11: ckodex.assurance.evidence.v1.EvidenceCompleteness
	(*timestamppb.Timestamp)(nil),    // 12: google.protobuf.Timestamp
	(*v1.AuthorityRef)(nil),          // 13: ckodex.assurance.common.v1.AuthorityRef
	(*durationpb.Duration)(nil),      // 14: google.protobuf.Duration
}
var file_assurance_assessment_v1_assessment_proto_depIdxs = []int32{
	5,  // 0: ckodex.assurance.assessment.v1.Claim.subject:type_name -> ckodex.assurance.common.v1.SubjectRef
	6,  // 1: ckodex.assurance.assessment.v1.Claim.control:type_name -> ckodex.assurance.control.v1.ControlRef
	7,  // 2: ckodex.assurance.assessment.v1.Claim.target_state:type_name -> ckodex.assurance.common.v1.AssuranceState
	6,  // 3: ckodex.assurance.assessment.v1.ClaimEvaluation.control:type_name -> ckodex.assurance.control.v1.ControlRef
	5,  // 4: ckodex.assurance.assessment.v1.ClaimEvaluation.subject:type_name -> ckodex.assurance.common.v1.SubjectRef
	7,  // 5: ckodex.assurance.assessment.v1.ClaimEvaluation.state:type_name -> ckodex.assurance.common.v1.AssuranceState
	8,  // 6: ckodex.assurance.assessment.v1.ClaimEvaluation.vector:type_name -> ckodex.assurance.common.v1.AssuranceVector
	9,  // 7: ckodex.assurance.assessment.v1.ClaimEvaluation.epoch:type_name -> ckodex.assurance.common.v1.AssuranceEpoch
	10, // 8: ckodex.assurance.assessment.v1.ClaimEvaluation.evidence:type_name -> ckodex.assurance.evidence.v1.EvidenceRef
	11, // 9: ckodex.assurance.assessment.v1.ClaimEvaluation.completeness:type_name -> ckodex.assurance.evidence.v1.EvidenceCompleteness
	12, // 10: ckodex.assurance.assessment.v1.ClaimEvaluation.evaluated_at:type_name -> google.protobuf.Timestamp
	12, // 11: ckodex.assurance.assessment.v1.ClaimEvaluation.valid_until:type_name -> google.protobuf.Timestamp
	5,  // 12: ckodex.assurance.assessment.v1.Finding.subject:type_name -> ckodex.assurance.common.v1.SubjectRef
	6,  // 13: ckodex.assurance.assessment.v1.Finding.control:type_name -> ckodex.assurance.control.v1.ControlRef
	12, // 14: ckodex.assurance.assessment.v1.Finding.discovered_at:type_name -> google.protobuf.Timestamp
	10, // 15: ckodex.assurance.assessment.v1.Finding.evidence_refs:type_name -> ckodex.assurance.evidence.v1.EvidenceRef
	5,  // 16: ckodex.assurance.assessment.v1.ControlException.subject:type_name -> ckodex.assurance.common.v1.SubjectRef
	6,  // 17: ckodex.assurance.assessment.v1.ControlException.controls:type_name -> ckodex.assurance.control.v1.ControlRef
	13, // 18: ckodex.assurance.assessment.v1.ControlException.required_approvers:type_name -> ckodex.assurance.common.v1.AuthorityRef
	12, // 19: ckodex.assurance.assessment.v1.ControlException.not_before:type_name -> google.protobuf.Timestamp
	12, // 20: ckodex.assurance.assessment.v1.ControlException.not_after:type_name -> google.protobuf.Timestamp
	6,  // 21: ckodex.assurance.assessment.v1.ControlException.compensating_controls:type_name -> ckodex.assurance.control.v1.ControlRef
	7,  // 22: ckodex.assurance.assessment.v1.AssurancePolicy.required_state:type_name -> ckodex.assurance.common.v1.AssuranceState
	14, // 23: ckodex.assurance.assessment.v1.AssurancePolicy.max_evaluation_age:type_name -> google.protobuf.Duration
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_assurance_assessment_v1_assessment_proto_init() }
func file_assurance_assessment_v1_assessment_proto_init() {
	if File_assurance_assessment_v1_assessment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_assurance_assessment_v1_assessment_proto_rawDesc), len(file_assurance_assessment_v1_assessment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_assurance_assessment_v1_assessment_proto_goTypes,
		DependencyIndexes: file_assurance_assessment_v1_assessment_proto_depIdxs,
		MessageInfos:      file_assurance_assessment_v1_assessment_proto_msgTypes,
	}.Build()
	File_assurance_assessment_v1_assessment_proto = out.File
	file_assurance_assessment_v1_assessment_proto_goTypes = nil
	file_assurance_assessment_v1_assessment_proto_depIdxs = nil
}
