// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: assurance/services/v1/assurance_service.proto

package servicesv1

import (
	v13 "github.com/ckodex-labs/ckodex-oskal/proto/assurance/assessment/v1"
	v11 "github.com/ckodex-labs/ckodex-oskal/proto/assurance/common/v1"
	v12 "github.com/ckodex-labs/ckodex-oskal/proto/assurance/control/v1"
	v1 "github.com/ckodex-labs/ckodex-oskal/proto/assurance/evidence/v1"
	v14 "github.com/ckodex-labs/ckodex-oskal/proto/assurance/receipt/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitObservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Observation   *v1.Observation        `protobuf:"bytes,1,opt,name=observation,proto3" json:"observation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitObservationRequest) Reset() {
	*x = SubmitObservationRequest{}
	mi := &file_assurance_services_v1_assurance_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitObservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitObservationRequest) ProtoMessage() {}

func (x *SubmitObservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assurance_services_v1_assurance_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitObservationRequest.ProtoReflect.Descriptor instead.
func (*SubmitObservationRequest) Descriptor() ([]byte, []int) {
	return file_assurance_services_v1_assurance_service_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitObservationRequest) GetObservation() *v1.Observation {
	if x != nil {
		return x.Observation
	}
	return nil
}

type SubmitObservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObservationId string                 `protobuf:"bytes,1,opt,name=observation_id,json=observationId,proto3" json:"observation_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitObservationResponse) Reset() {
	*x = SubmitObservationResponse{}
	mi := &file_assurance_services_v1_assurance_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitObservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitObservationResponse) ProtoMessage() {}

func (x *SubmitObservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assurance_services_v1_assurance_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitObservationResponse.ProtoReflect.Descriptor instead.
func (*SubmitObservationResponse) Descriptor() ([]byte, []int) {
	return file_assurance_services_v1_assurance_service_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitObservationResponse) GetObservationId() string {
	if x != nil {
		return x.ObservationId
	}
	return ""
}

func (x *SubmitObservationResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SubmitObservationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EvaluateSubjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       *v11.SubjectRef        `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Controls      []*v12.ControlRef      `protobuf:"bytes,2,rep,name=controls,proto3" json:"controls,omitempty"`
	ForceFresh    bool                   `protobuf:"varint,3,opt,name=force_fresh,json=forceFresh,proto3" json:"force_fresh,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateSubjectRequest) Reset() {
	*x = EvaluateSubjectRequest{}
	mi := &file_assurance_services_v1_assurance_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateSubjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateSubjectRequest) ProtoMessage() {}

func (x *EvaluateSubjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assurance_services_v1_assurance_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateSubjectRequest.ProtoReflect.Descriptor instead.
func (*EvaluateSubjectRequest) Descriptor() ([]byte, []int) {
	return file_assurance_services_v1_assurance_service_proto_rawDescGZIP(), []int{2}
}

func (x *EvaluateSubjectRequest) GetSubject() *v11.SubjectRef {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *EvaluateSubjectRequest) GetControls() []*v12.ControlRef {
	if x != nil {
		return x.Controls
	}
	return nil
}

func (x *EvaluateSubjectRequest) GetForceFresh() bool {
	if x != nil {
		return x.ForceFresh
	}
	return false
}

type EvaluateSubjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       *v11.SubjectRef        `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Evaluations   []*v13.ClaimEvaluation `protobuf:"bytes,2,rep,name=evaluations,proto3" json:"evaluations,omitempty"`
	SummaryState  v11.AssuranceState     `protobuf:"varint,3,opt,name=summary_state,json=summaryState,proto3,enum=ckodex.assurance.common.v1.AssuranceState" json:"summary_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateSubjectResponse) Reset() {
	*x = EvaluateSubjectResponse{}
	mi := &file_assurance_services_v1_assurance_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateSubjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateSubjectResponse) ProtoMessage() {}

func (x *EvaluateSubjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assurance_services_v1_assurance_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateSubjectResponse.ProtoReflect.Descriptor instead.
func (*EvaluateSubjectResponse) Descriptor() ([]byte, []int) {
	return file_assurance_services_v1_assurance_service_proto_rawDescGZIP(), []int{3}
}

func (x *EvaluateSubjectResponse) GetSubject() *v11.SubjectRef {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *EvaluateSubjectResponse) GetEvaluations() []*v13.ClaimEvaluation {
	if x != nil {
		return x.Evaluations
	}
	return nil
}

func (x *EvaluateSubjectResponse) GetSummaryState() v11.AssuranceState {
	if x != nil {
		return x.SummaryState
	}
	return v11.AssuranceState(0)
}

type ExplainClaimRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       *v11.SubjectRef        `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Control       *v12.ControlRef        `protobuf:"bytes,2,opt,name=control,proto3" json:"control,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainClaimRequest) Reset() {
	*x = ExplainClaimRequest{}
	mi := &file_assurance_services_v1_assurance_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainClaimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainClaimRequest) ProtoMessage() {}

func (x *ExplainClaimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assurance_services_v1_assurance_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainClaimRequest.ProtoReflect.Descriptor instead.
func (*ExplainClaimRequest) Descriptor() ([]byte, []int) {
	return file_assurance_services_v1_assurance_service_proto_rawDescGZIP(), []int{4}
}

func (x *ExplainClaimRequest) GetSubject() *v11.SubjectRef {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *ExplainClaimRequest) GetControl() *v12.ControlRef {
	if x != nil {
		return x.Control
	}
	return nil
}

type ExplainClaimResponse struct {
	state              protoimpl.MessageState   `protogen:"open.v1"`
	Subject            *v11.SubjectRef          `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Control            *v12.ControlRef          `protobuf:"bytes,2,opt,name=control,proto3" json:"control,omitempty"`
	CanonicalControl   string                   `protobuf:"bytes,3,opt,name=canonical_control,json=canonicalControl,proto3" json:"canonical_control,omitempty"`
	Applicability      string                   `protobuf:"bytes,4,opt,name=applicability,proto3" json:"applicability,omitempty"`
	AtomicRequirements []*v12.AtomicControl     `protobuf:"bytes,5,rep,name=atomic_requirements,json=atomicRequirements,proto3" json:"atomic_requirements,omitempty"`
	Implementations    []*v12.ImplementationRef `protobuf:"bytes,6,rep,name=implementations,proto3" json:"implementations,omitempty"`
	Evidence           []*v1.EvidenceRef        `protobuf:"bytes,7,rep,name=evidence,proto3" json:"evidence,omitempty"`
	Completeness       *v1.EvidenceCompleteness `protobuf:"bytes,8,opt,name=completeness,proto3" json:"completeness,omitempty"`
	Freshness          string                   `protobuf:"bytes,9,opt,name=freshness,proto3" json:"freshness,omitempty"`
	Authority          string                   `protobuf:"bytes,10,opt,name=authority,proto3" json:"authority,omitempty"`
	Epoch              *v11.AssuranceEpoch      `protobuf:"bytes,11,opt,name=epoch,proto3" json:"epoch,omitempty"`
	AssuranceState     v11.AssuranceState       `protobuf:"varint,12,opt,name=assurance_state,json=assuranceState,proto3,enum=ckodex.assurance.common.v1.AssuranceState" json:"assurance_state,omitempty"`
	EvidenceRoot       string                   `protobuf:"bytes,13,opt,name=evidence_root,json=evidenceRoot,proto3" json:"evidence_root,omitempty"`
	Projections        map[string]string        `protobuf:"bytes,14,rep,name=projections,proto3" json:"projections,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RenderedText       string                   `protobuf:"bytes,15,opt,name=rendered_text,json=renderedText,proto3" json:"rendered_text,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ExplainClaimResponse) Reset() {
	*x = ExplainClaimResponse{}
	mi := &file_assurance_services_v1_assurance_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainClaimResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainClaimResponse) ProtoMessage() {}

func (x *ExplainClaimResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assurance_services_v1_assurance_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainClaimResponse.ProtoReflect.Descriptor instead.
func (*ExplainClaimResponse) Descriptor() ([]byte, []int) {
	return file_assurance_services_v1_assurance_service_proto_rawDescGZIP(), []int{5}
}

func (x *ExplainClaimResponse) GetSubject() *v11.SubjectRef {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *ExplainClaimResponse) GetControl() *v12.ControlRef {
	if x != nil {
		return x.Control
	}
	return nil
}

func (x *ExplainClaimResponse) GetCanonicalControl() string {
	if x != nil {
		return x.CanonicalControl
	}
	return ""
}

func (x *ExplainClaimResponse) GetApplicability() string {
	if x != nil {
		return x.Applicability
	}
	return ""
}

func (x *ExplainClaimResponse) GetAtomicRequirements() []*v12.AtomicControl {
	if x != nil {
		return x.AtomicRequirements
	}
	return nil
}

func (x *ExplainClaimResponse) GetImplementations() []*v12.ImplementationRef {
	if x != nil {
		return x.Implementations
	}
	return nil
}

func (x *ExplainClaimResponse) GetEvidence() []*v1.EvidenceRef {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *ExplainClaimResponse) GetCompleteness() *v1.EvidenceCompleteness {
	if x != nil {
		return x.Completeness
	}
	return nil
}

func (x *ExplainClaimResponse) GetFreshness() string {
	if x != nil {
		return x.Freshness
	}
	return ""
}

func (x *ExplainClaimResponse) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *ExplainClaimResponse) GetEpoch() *v11.AssuranceEpoch {
	if x != nil {
		return x.Epoch
	}
	return nil
}

func (x *ExplainClaimResponse) GetAssuranceState() v11.AssuranceState {
	if x != nil {
		return x.AssuranceState
	}
	return v11.AssuranceState(0)
}

func (x *ExplainClaimResponse) GetEvidenceRoot() string {
	if x != nil {
		return x.EvidenceRoot
	}
	return ""
}

func (x *ExplainClaimResponse) GetProjections() map[string]string {
	if x != nil {
		return x.Projections
	}
	return nil
}

func (x *ExplainClaimResponse) GetRenderedText() string {
	if x != nil {
		return x.RenderedText
	}
	return ""
}

type GetAssuranceStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       *v11.SubjectRef        `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssuranceStateRequest) Reset() {
	*x = GetAssuranceStateRequest{}
	mi := &file_assurance_services_v1_assurance_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssuranceStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssuranceStateRequest) ProtoMessage() {}

func (x *GetAssuranceStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assurance_services_v1_assurance_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssuranceStateRequest.ProtoReflect.Descriptor instead.
func (*GetAssuranceStateRequest) Descriptor() ([]byte, []int) {
	return file_assurance_services_v1_assurance_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetAssuranceStateRequest) GetSubject() *v11.SubjectRef {
	if x != nil {
		return x.Subject
	}
	return nil
}

type GetAssuranceStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       *v11.SubjectRef        `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	State         v11.AssuranceState     `protobuf:"varint,2,opt,name=state,proto3,enum=ckodex.assurance.common.v1.AssuranceState" json:"state,omitempty"`
	Epoch         *v11.AssuranceEpoch    `protobuf:"bytes,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	EvidenceRoot  string                 `protobuf:"bytes,4,opt,name=evidence_root,json=evidenceRoot,proto3" json:"evidence_root,omitempty"`
	Evaluations   []*v13.ClaimEvaluation `protobuf:"bytes,5,rep,name=evaluations,proto3" json:"evaluations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssuranceStateResponse) Reset() {
	*x = GetAssuranceStateResponse{}
	mi := &file_assurance_services_v1_assurance_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssuranceStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssuranceStateResponse) ProtoMessage() {}

func (x *GetAssuranceStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assurance_services_v1_assurance_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssuranceStateResponse.ProtoReflect.Descriptor instead.
func (*GetAssuranceStateResponse) Descriptor() ([]byte, []int) {
	return file_assurance_services_v1_assurance_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetAssuranceStateResponse) GetSubject() *v11.SubjectRef {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *GetAssuranceStateResponse) GetState() v11.AssuranceState {
	if x != nil {
		return x.State
	}
	return v11.AssuranceState(0)
}

func (x *GetAssuranceStateResponse) GetEpoch() *v11.AssuranceEpoch {
	if x != nil {
		return x.Epoch
	}
	return nil
}

func (x *GetAssuranceStateResponse) GetEvidenceRoot() string {
	if x != nil {
		return x.EvidenceRoot
	}
	return ""
}

func (x *GetAssuranceStateResponse) GetEvaluations() []*v13.ClaimEvaluation {
	if x != nil {
		return x.Evaluations
	}
	return nil
}

type SubmitReceiptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receipt       *v14.ControlReceipt    `protobuf:"bytes,1,opt,name=receipt,proto3" json:"receipt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitReceiptRequest) Reset() {
	*x = SubmitReceiptRequest{}
	mi := &file_assurance_services_v1_assurance_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitReceiptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitReceiptRequest) ProtoMessage() {}

func (x *SubmitReceiptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assurance_services_v1_assurance_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitReceiptRequest.ProtoReflect.Descriptor instead.
func (*SubmitReceiptRequest) Descriptor() ([]byte, []int) {
	return file_assurance_services_v1_assurance_service_proto_rawDescGZIP(), []int{8}
}

func (x *SubmitReceiptRequest) GetReceipt() *v14.ControlReceipt {
	if x != nil {
		return x.Receipt
	}
	return nil
}

type SubmitReceiptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verified      bool                   `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`
	ReceiptDigest string                 `protobuf:"bytes,2,opt,name=receipt_digest,json=receiptDigest,proto3" json:"receipt_digest,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitReceiptResponse) Reset() {
	*x = SubmitReceiptResponse{}
	mi := &file_assurance_services_v1_assurance_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitReceiptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitReceiptResponse) ProtoMessage() {}

func (x *SubmitReceiptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assurance_services_v1_assurance_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitReceiptResponse.ProtoReflect.Descriptor instead.
func (*SubmitReceiptResponse) Descriptor() ([]byte, []int) {
	return file_assurance_services_v1_assurance_service_proto_rawDescGZIP(), []int{9}
}

func (x *SubmitReceiptResponse) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *SubmitReceiptResponse) GetReceiptDigest() string {
	if x != nil {
		return x.ReceiptDigest
	}
	return ""
}

func (x *SubmitReceiptResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_assurance_services_v1_assurance_service_proto protoreflect.FileDescriptor

const file_assurance_services_v1_assurance_service_proto_rawDesc = "" +
	"\n" +
	"-assurance/services/v1/assurance_service.proto\x12\x1cckodex.assurance.services.v1\x1a assurance/common/v1/common.proto\x1a\"assurance/control/v1/control.proto\x1a$assurance/evidence/v1/evidence.proto\x1a(assurance/assessment/v1/assessment.proto\x1a\"assurance/receipt/v1/receipt.proto\"g\n" +
	"\x18SubmitObservationRequest\x12K\n" +
	"\vobservation\x18\x01 \x01(\v2).ckodex.assurance.evidence.v1.ObservationR\vobservation\"x\n" +
	"\x19SubmitObservationResponse\x12%\n" +
	"\x0eobservation_id\x18\x01 \x01(\tR\robservationId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xc0\x01\n" +
	"\x16EvaluateSubjectRequest\x12@\n" +
	"\asubject\x18\x01 \x01(\v2&.ckodex.assurance.common.v1.SubjectRefR\asubject\x12C\n" +
	"\bcontrols\x18\x02 \x03(\v2'.ckodex.assurance.control.v1.ControlRefR\bcontrols\x12\x1f\n" +
	"\vforce_fresh\x18\x03 \x01(\bR\n" +
	"forceFresh\"\xff\x01\n" +
	"\x17EvaluateSubjectResponse\x12@\n" +
	"\asubject\x18\x01 \x01(\v2&.ckodex.assurance.common.v1.SubjectRefR\asubject\x12Q\n" +
	"\vevaluations\x18\x02 \x03(\v2/.ckodex.assurance.assessment.v1.ClaimEvaluationR\vevaluations\x12O\n" +
	"\rsummary_state\x18\x03 \x01(\x0e2*.ckodex.assurance.common.v1.AssuranceStateR\fsummaryState\"\x9a\x01\n" +
	"\x13ExplainClaimRequest\x12@\n" +
	"\asubject\x18\x01 \x01(\v2&.ckodex.assurance.common.v1.SubjectRefR\asubject\x12A\n" +
	"\acontrol\x18\x02 \x01(\v2'.ckodex.assurance.control.v1.ControlRefR\acontrol\"\x88\b\n" +
	"\x14ExplainClaimResponse\x12@\n" +
	"\asubject\x18\x01 \x01(\v2&.ckodex.assurance.common.v1.SubjectRefR\asubject\x12A\n" +
	"\acontrol\x18\x02 \x01(\v2'.ckodex.assurance.control.v1.ControlRefR\acontrol\x12+\n" +
	"\x11canonical_control\x18\x03 \x01(\tR\x10canonicalControl\x12$\n" +
	"\rapplicability\x18\x04 \x01(\tR\rapplicability\x12[\n" +
	"\x13atomic_requirements\x18\x05 \x03(\v2*.ckodex.assurance.control.v1.AtomicControlR\x12atomicRequirements\x12X\n" +
	"\x0fimplementations\x18\x06 \x03(\v2..ckodex.assurance.control.v1.ImplementationRefR\x0fimplementations\x12E\n" +
	"\bevidence\x18\a \x03(\v2).ckodex.assurance.evidence.v1.EvidenceRefR\bevidence\x12V\n" +
	"\fcompleteness\x18\b \x01(\v22.ckodex.assurance.evidence.v1.EvidenceCompletenessR\fcompleteness\x12\x1c\n" +
	"\tfreshness\x18\t \x01(\tR\tfreshness\x12\x1c\n" +
	"\tauthority\x18\n" +
	" \x01(\tR\tauthority\x12@\n" +
	"\x05epoch\x18\v \x01(\v2*.ckodex.assurance.common.v1.AssuranceEpochR\x05epoch\x12S\n" +
	"\x0fassurance_state\x18\f \x01(\x0e2*.ckodex.assurance.common.v1.AssuranceStateR\x0eassuranceState\x12#\n" +
	"\revidence_root\x18\r \x01(\tR\fevidenceRoot\x12e\n" +
	"\vprojections\x18\x0e \x03(\v2C.ckodex.assurance.services.v1.ExplainClaimResponse.ProjectionsEntryR\vprojections\x12#\n" +
	"\rrendered_text\x18\x0f \x01(\tR\frenderedText\x1a>\n" +
	"\x10ProjectionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\\\n" +
	"\x18GetAssuranceStateRequest\x12@\n" +
	"\asubject\x18\x01 \x01(\v2&.ckodex.assurance.common.v1.SubjectRefR\asubject\"\xd9\x02\n" +
	"\x19GetAssuranceStateResponse\x12@\n" +
	"\asubject\x18\x01 \x01(\v2&.ckodex.assurance.common.v1.SubjectRefR\asubject\x12@\n" +
	"\x05state\x18\x02 \x01(\x0e2*.ckodex.assurance.common.v1.AssuranceStateR\x05state\x12@\n" +
	"\x05epoch\x18\x03 \x01(\v2*.ckodex.assurance.common.v1.AssuranceEpochR\x05epoch\x12#\n" +
	"\revidence_root\x18\x04 \x01(\tR\fevidenceRoot\x12Q\n" +
	"\vevaluations\x18\x05 \x03(\v2/.ckodex.assurance.assessment.v1.ClaimEvaluationR\vevaluations\"]\n" +
	"\x14SubmitReceiptRequest\x12E\n" +
	"\areceipt\x18\x01 \x01(\v2+.ckodex.assurance.receipt.v1.ControlReceiptR\areceipt\"t\n" +
	"\x15SubmitReceiptResponse\x12\x1a\n" +
	"\bverified\x18\x01 \x01(\bR\bverified\x12%\n" +
	"\x0ereceipt_digest\x18\x02 \x01(\tR\rreceiptDigest\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\x91\x05\n" +
	"\x10AssuranceService\x12\x84\x01\n" +
	"\x11SubmitObservation\x126.ckodex.assurance.services.v1.SubmitObservationRequest\x1a7.ckodex.assurance.services.v1.SubmitObservationResponse\x12~\n" +
	"\x0fEvaluateSubject\x124.ckodex.assurance.services.v1.EvaluateSubjectRequest\x1a5.ckodex.assurance.services.v1.EvaluateSubjectResponse\x12u\n" +
	"\fExplainClaim\x121.ckodex.assurance.services.v1.ExplainClaimRequest\x1a2.ckodex.assurance.services.v1.ExplainClaimResponse\x12\x84\x01\n" +
	"\x11GetAssuranceState\x126.ckodex.assurance.services.v1.GetAssuranceStateRequest\x1a7.ckodex.assurance.services.v1.GetAssuranceStateResponse\x12x\n" +
	"\rSubmitReceipt\x122.ckodex.assurance.services.v1.SubmitReceiptRequest\x1a3.ckodex.assurance.services.v1.SubmitReceiptResponseBLZJgithub.com/ckodex-labs/ckodex-oskal/proto/assurance/services/v1;servicesv1b\x06proto3"

var (
	file_assurance_services_v1_assurance_service_proto_rawDescOnce sync.Once
	file_assurance_services_v1_assurance_service_proto_rawDescData []byte
)

func file_assurance_services_v1_assurance_service_proto_rawDescGZIP() []byte {
	file_assurance_services_v1_assurance_service_proto_rawDescOnce.Do(func() {
		file_assurance_services_v1_assurance_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_assurance_services_v1_assurance_service_proto_rawDesc), len(file_assurance_services_v1_assurance_service_proto_rawDesc)))
	})
	return file_assurance_services_v1_assurance_service_proto_rawDescData
}

var file_assurance_services_v1_assurance_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_assurance_services_v1_assurance_service_proto_goTypes = []any{
	(*SubmitObservationRequest)(nil),  // 0: ckodex.assurance.services.v1.SubmitObservationRequest
	(*SubmitObservationResponse)(nil), // 1: ckodex.assurance.services.v1.SubmitObservationResponse
	(*EvaluateSubjectRequest)(nil),    // 2: ckodex.assurance.services.v1.EvaluateSubjectRequest
	(*EvaluateSubjectResponse)(nil),   // 3: ckodex.assurance.services.v1.EvaluateSubjectResponse
	(*ExplainClaimRequest)(nil),       // 4: ckodex.assurance.services.v1.ExplainClaimRequest
	(*ExplainClaimResponse)(nil),      // 5: ckodex.assurance.services.v1.ExplainClaimResponse
	(*GetAssuranceStateRequest)(nil),  // 6: ckodex.assurance.services.v1.GetAssuranceStateRequest
	(*GetAssuranceStateResponse)(nil), // 7: ckodex.assurance.services.v1.GetAssuranceStateResponse
	(*SubmitReceiptRequest)(nil),      // 8: ckodex.assurance.services.v1.SubmitReceiptRequest
	(*SubmitReceiptResponse)(nil),     // 9: ckodex.assurance.services.v1.SubmitReceiptResponse
	nil,                               // 10: ckodex.assurance.services.v1.ExplainClaimResponse.ProjectionsEntry
	(*v1.Observation)(nil),            // 11: ckodex.assurance.evidence.v1.Observation
	(*v11.SubjectRef)(nil),            // 12: ckodex.assurance.common.v1.SubjectRef
	(*v12.ControlRef)(nil),            // 13: ckodex.assurance.control.v1.ControlRef
	(*v13.ClaimEvaluation)(nil),       // 14: ckodex.assurance.assessment.v1.ClaimEvaluation
	(v11.AssuranceState)(0),           // 15: ckodex.assurance.common.v1.AssuranceState
	(*v12.AtomicControl)(nil),         // 16: ckodex.assurance.control.v1.AtomicControl
	(*v12.ImplementationRef)(nil),     // 17: ckodex.assurance.control.v1.ImplementationRef
	(*v1.EvidenceRef)(nil),            // 18: ckodex.assurance.evidence.v1.EvidenceRef
	(*v1.EvidenceCompleteness)(nil),   // 19: ckodex.assurance.evidence.v1.EvidenceCompleteness
	(*v11.AssuranceEpoch)(nil),        // 20: ckodex.assurance.common.v1.AssuranceEpoch
	(*v14.ControlReceipt)(nil),        // 21: ckodex.assurance.receipt.v1.ControlReceipt
}
var file_assurance_services_v1_assurance_service_proto_depIdxs = []int32{
	11, // 0: ckodex.assurance.services.v1.SubmitObservationRequest.observation:type_name -> ckodex.assurance.evidence.v1.Observation
	12, // 1: ckodex.assurance.services.v1.EvaluateSubjectRequest.subject:type_name -> ckodex.assurance.common.v1.SubjectRef
	13, // 2: ckodex.assurance.services.v1.EvaluateSubjectRequest.controls:type_name -> ckodex.assurance.control.v1.ControlRef
	12, // 3: ckodex.assurance.services.v1.EvaluateSubjectResponse.subject:type_name -> ckodex.assurance.common.v1.SubjectRef
	14, // 4: ckodex.assurance.services.v1.EvaluateSubjectResponse.evaluations:type_name -> ckodex.assurance.assessment.v1.ClaimEvaluation
	15, // 5: ckodex.assurance.services.v1.EvaluateSubjectResponse.summary_state:type_name -> ckodex.assurance.common.v1.AssuranceState
	12, // 6: ckodex.assurance.services.v1.ExplainClaimRequest.subject:type_name -> ckodex.assurance.common.v1.SubjectRef
	13, // 7: ckodex.assurance.services.v1.ExplainClaimRequest.control:type_name -> ckodex.assurance.control.v1.ControlRef
	12, // 8: ckodex.assurance.services.v1.ExplainClaimResponse.subject:type_name -> ckodex.assurance.common.v1.SubjectRef
	13, // 9: ckodex.assurance.services.v1.ExplainClaimResponse.control:type_name -> ckodex.assurance.control.v1.ControlRef
	16, // 10: ckodex.assurance.services.v1.ExplainClaimResponse.atomic_requirements:type_name -> ckodex.assurance.control.v1.AtomicControl
	17, // 11: ckodex.assurance.services.v1.ExplainClaimResponse.implementations:type_name -> ckodex.assurance.control.v1.ImplementationRef
	18, // 12: ckodex.assurance.services.v1.ExplainClaimResponse.evidence:type_name -> ckodex.assurance.evidence.v1.EvidenceRef
	19, // 13: ckodex.assurance.services.v1.ExplainClaimResponse.completeness:type_name -> ckodex.assurance.evidence.v1.EvidenceCompleteness
	20, // 14: ckodex.assurance.services.v1.ExplainClaimResponse.epoch:type_name -> ckodex.assurance.common.v1.AssuranceEpoch
	15, // 15: ckodex.assurance.services.v1.ExplainClaimResponse.assurance_state:type_name -> ckodex.assurance.common.v1.AssuranceState
	10, // 16: ckodex.assurance.services.v1.ExplainClaimResponse.projections:type_name -> ckodex.assurance.services.v1.ExplainClaimResponse.ProjectionsEntry
	12, // 17: ckodex.assurance.services.v1.GetAssuranceStateRequest.subject:type_name -> ckodex.assurance.common.v1.SubjectRef
	12, // 18: ckodex.assurance.services.v1.GetAssuranceStateResponse.subject:type_name -> ckodex.assurance.common.v1.SubjectRef
	15, // 19: ckodex.assurance.services.v1.GetAssuranceStateResponse.state:type_name -> ckodex.assurance.common.v1.AssuranceState
	20, // 20: ckodex.assurance.services.v1.GetAssuranceStateResponse.epoch:type_name -> ckodex.assurance.common.v1.AssuranceEpoch
	14, // 21: ckodex.assurance.services.v1.GetAssuranceStateResponse.evaluations:type_name -> ckodex.assurance.assessment.v1.ClaimEvaluation
	21, // 22: ckodex.assurance.services.v1.SubmitReceiptRequest.receipt:type_name -> ckodex.assurance.receipt.v1.ControlReceipt
	0,  // 23: ckodex.assurance.services.v1.AssuranceService.SubmitObservation:input_type -> ckodex.assurance.services.v1.SubmitObservationRequest
	2,  // 24: ckodex.assurance.services.v1.AssuranceService.EvaluateSubject:input_type -> ckodex.assurance.services.v1.EvaluateSubjectRequest
	4,  // 25: ckodex.assurance.services.v1.AssuranceService.ExplainClaim:input_type -> ckodex.assurance.services.v1.ExplainClaimRequest
	6,  // 26: ckodex.assurance.services.v1.AssuranceService.GetAssuranceState:input_type -> ckodex.assurance.services.v1.GetAssuranceStateRequest
	8,  // 27: ckodex.assurance.services.v1.AssuranceService.SubmitReceipt:input_type -> ckodex.assurance.services.v1.SubmitReceiptRequest
	1,  // 28: ckodex.assurance.services.v1.AssuranceService.SubmitObservation:output_type -> ckodex.assurance.services.v1.SubmitObservationResponse
	3,  // 29: ckodex.assurance.services.v1.AssuranceService.EvaluateSubject:output_type -> ckodex.assurance.services.v1.EvaluateSubjectResponse
	5,  // 30: ckodex.assurance.services.v1.AssuranceService.ExplainClaim:output_type -> ckodex.assurance.services.v1.ExplainClaimResponse
	7,  // 31: ckodex.assurance.services.v1.AssuranceService.GetAssuranceState:output_type -> ckodex.assurance.services.v1.GetAssuranceStateResponse
	9,  // 32: ckodex.assurance.services.v1.AssuranceService.SubmitReceipt:output_type -> ckodex.assurance.services.v1.SubmitReceiptResponse
	28, // [28:33] is the sub-list for method output_type
	23, // [23:28] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_assurance_services_v1_assurance_service_proto_init() }
func file_assurance_services_v1_assurance_service_proto_init() {
	if File_assurance_services_v1_assurance_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_assurance_services_v1_assurance_service_proto_rawDesc), len(file_assurance_services_v1_assurance_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_assurance_services_v1_assurance_service_proto_goTypes,
		DependencyIndexes: file_assurance_services_v1_assurance_service_proto_depIdxs,
		MessageInfos:      file_assurance_services_v1_assurance_service_proto_msgTypes,
	}.Build()
	File_assurance_services_v1_assurance_service_proto = out.File
	file_assurance_services_v1_assurance_service_proto_goTypes = nil
	file_assurance_services_v1_assurance_service_proto_depIdxs = nil
}
