// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: assurance/services/v1/assurance_service.proto

package servicesv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AssuranceService_SubmitObservation_FullMethodName = "/ckodex.assurance.services.v1.AssuranceService/SubmitObservation"
	AssuranceService_EvaluateSubject_FullMethodName   = "/ckodex.assurance.services.v1.AssuranceService/EvaluateSubject"
	AssuranceService_ExplainClaim_FullMethodName      = "/ckodex.assurance.services.v1.AssuranceService/ExplainClaim"
	AssuranceService_GetAssuranceState_FullMethodName = "/ckodex.assurance.services.v1.AssuranceService/GetAssuranceState"
	AssuranceService_SubmitReceipt_FullMethodName     = "/ckodex.assurance.services.v1.AssuranceService/SubmitReceipt"
)

// AssuranceServiceClient is the client API for AssuranceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssuranceServiceClient interface {
	SubmitObservation(ctx context.Context, in *SubmitObservationRequest, opts ...grpc.CallOption) (*SubmitObservationResponse, error)
	EvaluateSubject(ctx context.Context, in *EvaluateSubjectRequest, opts ...grpc.CallOption) (*EvaluateSubjectResponse, error)
	ExplainClaim(ctx context.Context, in *ExplainClaimRequest, opts ...grpc.CallOption) (*ExplainClaimResponse, error)
	GetAssuranceState(ctx context.Context, in *GetAssuranceStateRequest, opts ...grpc.CallOption) (*GetAssuranceStateResponse, error)
	SubmitReceipt(ctx context.Context, in *SubmitReceiptRequest, opts ...grpc.CallOption) (*SubmitReceiptResponse, error)
}

type assuranceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAssuranceServiceClient(cc grpc.ClientConnInterface) AssuranceServiceClient {
	return &assuranceServiceClient{cc}
}

func (c *assuranceServiceClient) SubmitObservation(ctx context.Context, in *SubmitObservationRequest, opts ...grpc.CallOption) (*SubmitObservationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitObservationResponse)
	err := c.cc.Invoke(ctx, AssuranceService_SubmitObservation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assuranceServiceClient) EvaluateSubject(ctx context.Context, in *EvaluateSubjectRequest, opts ...grpc.CallOption) (*EvaluateSubjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateSubjectResponse)
	err := c.cc.Invoke(ctx, AssuranceService_EvaluateSubject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assuranceServiceClient) ExplainClaim(ctx context.Context, in *ExplainClaimRequest, opts ...grpc.CallOption) (*ExplainClaimResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExplainClaimResponse)
	err := c.cc.Invoke(ctx, AssuranceService_ExplainClaim_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assuranceServiceClient) GetAssuranceState(ctx context.Context, in *GetAssuranceStateRequest, opts ...grpc.CallOption) (*GetAssuranceStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAssuranceStateResponse)
	err := c.cc.Invoke(ctx, AssuranceService_GetAssuranceState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assuranceServiceClient) SubmitReceipt(ctx context.Context, in *SubmitReceiptRequest, opts ...grpc.CallOption) (*SubmitReceiptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitReceiptResponse)
	err := c.cc.Invoke(ctx, AssuranceService_SubmitReceipt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssuranceServiceServer is the server API for AssuranceService service.
// All implementations must embed UnimplementedAssuranceServiceServer
// for forward compatibility.
type AssuranceServiceServer interface {
	SubmitObservation(context.Context, *SubmitObservationRequest) (*SubmitObservationResponse, error)
	EvaluateSubject(context.Context, *EvaluateSubjectRequest) (*EvaluateSubjectResponse, error)
	ExplainClaim(context.Context, *ExplainClaimRequest) (*ExplainClaimResponse, error)
	GetAssuranceState(context.Context, *GetAssuranceStateRequest) (*GetAssuranceStateResponse, error)
	SubmitReceipt(context.Context, *SubmitReceiptRequest) (*SubmitReceiptResponse, error)
	mustEmbedUnimplementedAssuranceServiceServer()
}

// UnimplementedAssuranceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAssuranceServiceServer struct{}

func (UnimplementedAssuranceServiceServer) SubmitObservation(context.Context, *SubmitObservationRequest) (*SubmitObservationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitObservation not implemented")
}
func (UnimplementedAssuranceServiceServer) EvaluateSubject(context.Context, *EvaluateSubjectRequest) (*EvaluateSubjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvaluateSubject not implemented")
}
func (UnimplementedAssuranceServiceServer) ExplainClaim(context.Context, *ExplainClaimRequest) (*ExplainClaimResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExplainClaim not implemented")
}
func (UnimplementedAssuranceServiceServer) GetAssuranceState(context.Context, *GetAssuranceStateRequest) (*GetAssuranceStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAssuranceState not implemented")
}
func (UnimplementedAssuranceServiceServer) SubmitReceipt(context.Context, *SubmitReceiptRequest) (*SubmitReceiptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitReceipt not implemented")
}
func (UnimplementedAssuranceServiceServer) mustEmbedUnimplementedAssuranceServiceServer() {}
func (UnimplementedAssuranceServiceServer) testEmbeddedByValue()                          {}

// UnsafeAssuranceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssuranceServiceServer will
// result in compilation errors.
type UnsafeAssuranceServiceServer interface {
	mustEmbedUnimplementedAssuranceServiceServer()
}

func RegisterAssuranceServiceServer(s grpc.ServiceRegistrar, srv AssuranceServiceServer) {
	// If the following call pancis, it indicates UnimplementedAssuranceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AssuranceService_ServiceDesc, srv)
}

func _AssuranceService_SubmitObservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitObservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssuranceServiceServer).SubmitObservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssuranceService_SubmitObservation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssuranceServiceServer).SubmitObservation(ctx, req.(*SubmitObservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssuranceService_EvaluateSubject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateSubjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssuranceServiceServer).EvaluateSubject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssuranceService_EvaluateSubject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssuranceServiceServer).EvaluateSubject(ctx, req.(*EvaluateSubjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssuranceService_ExplainClaim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExplainClaimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssuranceServiceServer).ExplainClaim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssuranceService_ExplainClaim_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssuranceServiceServer).ExplainClaim(ctx, req.(*ExplainClaimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssuranceService_GetAssuranceState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssuranceStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssuranceServiceServer).GetAssuranceState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssuranceService_GetAssuranceState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssuranceServiceServer).GetAssuranceState(ctx, req.(*GetAssuranceStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssuranceService_SubmitReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitReceiptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssuranceServiceServer).SubmitReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssuranceService_SubmitReceipt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssuranceServiceServer).SubmitReceipt(ctx, req.(*SubmitReceiptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AssuranceService_ServiceDesc is the grpc.ServiceDesc for AssuranceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssuranceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ckodex.assurance.services.v1.AssuranceService",
	HandlerType: (*AssuranceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitObservation",
			Handler:    _AssuranceService_SubmitObservation_Handler,
		},
		{
			MethodName: "EvaluateSubject",
			Handler:    _AssuranceService_EvaluateSubject_Handler,
		},
		{
			MethodName: "ExplainClaim",
			Handler:    _AssuranceService_ExplainClaim_Handler,
		},
		{
			MethodName: "GetAssuranceState",
			Handler:    _AssuranceService_GetAssuranceState_Handler,
		},
		{
			MethodName: "SubmitReceipt",
			Handler:    _AssuranceService_SubmitReceipt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "assurance/services/v1/assurance_service.proto",
}
