//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdmissionEnforcementConfig) DeepCopyInto(out *AdmissionEnforcementConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdmissionEnforcementConfig.
func (in *AdmissionEnforcementConfig) DeepCopy() *AdmissionEnforcementConfig {
	if in == nil {
		return nil
	}
	out := new(AdmissionEnforcementConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssurancePolicy) DeepCopyInto(out *AssurancePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssurancePolicy.
func (in *AssurancePolicy) DeepCopy() *AssurancePolicy {
	if in == nil {
		return nil
	}
	out := new(AssurancePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AssurancePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssurancePolicyList) DeepCopyInto(out *AssurancePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AssurancePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssurancePolicyList.
func (in *AssurancePolicyList) DeepCopy() *AssurancePolicyList {
	if in == nil {
		return nil
	}
	out := new(AssurancePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AssurancePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssurancePolicySpec) DeepCopyInto(out *AssurancePolicySpec) {
	*out = *in
	out.Evidence = in.Evidence
	out.Behavior = in.Behavior
	out.Freshness = in.Freshness
	out.Enforcement = in.Enforcement
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssurancePolicySpec.
func (in *AssurancePolicySpec) DeepCopy() *AssurancePolicySpec {
	if in == nil {
		return nil
	}
	out := new(AssurancePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssurancePolicyStatus) DeepCopyInto(out *AssurancePolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssurancePolicyStatus.
func (in *AssurancePolicyStatus) DeepCopy() *AssurancePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(AssurancePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssuranceState) DeepCopyInto(out *AssuranceState) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssuranceState.
func (in *AssuranceState) DeepCopy() *AssuranceState {
	if in == nil {
		return nil
	}
	out := new(AssuranceState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AssuranceState) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssuranceStateList) DeepCopyInto(out *AssuranceStateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AssuranceState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssuranceStateList.
func (in *AssuranceStateList) DeepCopy() *AssuranceStateList {
	if in == nil {
		return nil
	}
	out := new(AssuranceStateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AssuranceStateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssuranceStateSpec) DeepCopyInto(out *AssuranceStateSpec) {
	*out = *in
	out.SubjectRef = in.SubjectRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssuranceStateSpec.
func (in *AssuranceStateSpec) DeepCopy() *AssuranceStateSpec {
	if in == nil {
		return nil
	}
	out := new(AssuranceStateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssuranceStateStatus) DeepCopyInto(out *AssuranceStateStatus) {
	*out = *in
	out.Epoch = in.Epoch
	if in.Controls != nil {
		in, out := &in.Controls, &out.Controls
		*out = make([]ControlStatus, len(*in))
		copy(*out, *in)
	}
	if in.EvaluatedAt != nil {
		in, out := &in.EvaluatedAt, &out.EvaluatedAt
		*out = (*in).DeepCopy()
	}
	if in.ValidUntil != nil {
		in, out := &in.ValidUntil, &out.ValidUntil
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssuranceStateStatus.
func (in *AssuranceStateStatus) DeepCopy() *AssuranceStateStatus {
	if in == nil {
		return nil
	}
	out := new(AssuranceStateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CanonicalControlRef) DeepCopyInto(out *CanonicalControlRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CanonicalControlRef.
func (in *CanonicalControlRef) DeepCopy() *CanonicalControlRef {
	if in == nil {
		return nil
	}
	out := new(CanonicalControlRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContractRequirement) DeepCopyInto(out *ContractRequirement) {
	*out = *in
	out.Freshness = in.Freshness
	if in.AcceptedProducers != nil {
		in, out := &in.AcceptedProducers, &out.AcceptedProducers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContractRequirement.
func (in *ContractRequirement) DeepCopy() *ContractRequirement {
	if in == nil {
		return nil
	}
	out := new(ContractRequirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlBinding) DeepCopyInto(out *ControlBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlBinding.
func (in *ControlBinding) DeepCopy() *ControlBinding {
	if in == nil {
		return nil
	}
	out := new(ControlBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControlBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlBindingItem) DeepCopyInto(out *ControlBindingItem) {
	*out = *in
	out.Canonical = in.Canonical
	if in.Mappings != nil {
		in, out := &in.Mappings, &out.Mappings
		*out = make([]FrameworkMapping, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlBindingItem.
func (in *ControlBindingItem) DeepCopy() *ControlBindingItem {
	if in == nil {
		return nil
	}
	out := new(ControlBindingItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlBindingList) DeepCopyInto(out *ControlBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ControlBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlBindingList.
func (in *ControlBindingList) DeepCopy() *ControlBindingList {
	if in == nil {
		return nil
	}
	out := new(ControlBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControlBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlBindingSpec) DeepCopyInto(out *ControlBindingSpec) {
	*out = *in
	if in.Controls != nil {
		in, out := &in.Controls, &out.Controls
		*out = make([]ControlBindingItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Subjects.DeepCopyInto(&out.Subjects)
	if in.Requirements != nil {
		in, out := &in.Requirements, &out.Requirements
		*out = make([]RequirementBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlBindingSpec.
func (in *ControlBindingSpec) DeepCopy() *ControlBindingSpec {
	if in == nil {
		return nil
	}
	out := new(ControlBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlBindingStatus) DeepCopyInto(out *ControlBindingStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlBindingStatus.
func (in *ControlBindingStatus) DeepCopy() *ControlBindingStatus {
	if in == nil {
		return nil
	}
	out := new(ControlBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlException) DeepCopyInto(out *ControlException) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlException.
func (in *ControlException) DeepCopy() *ControlException {
	if in == nil {
		return nil
	}
	out := new(ControlException)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControlException) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlExceptionList) DeepCopyInto(out *ControlExceptionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ControlException, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlExceptionList.
func (in *ControlExceptionList) DeepCopy() *ControlExceptionList {
	if in == nil {
		return nil
	}
	out := new(ControlExceptionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControlExceptionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlExceptionSpec) DeepCopyInto(out *ControlExceptionSpec) {
	*out = *in
	out.Subject = in.Subject
	if in.Controls != nil {
		in, out := &in.Controls, &out.Controls
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Justification = in.Justification
	in.Authority.DeepCopyInto(&out.Authority)
	in.Validity.DeepCopyInto(&out.Validity)
	if in.CompensatingControls != nil {
		in, out := &in.CompensatingControls, &out.CompensatingControls
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlExceptionSpec.
func (in *ControlExceptionSpec) DeepCopy() *ControlExceptionSpec {
	if in == nil {
		return nil
	}
	out := new(ControlExceptionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlExceptionStatus) DeepCopyInto(out *ControlExceptionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlExceptionStatus.
func (in *ControlExceptionStatus) DeepCopy() *ControlExceptionStatus {
	if in == nil {
		return nil
	}
	out := new(ControlExceptionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlStatus) DeepCopyInto(out *ControlStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlStatus.
func (in *ControlStatus) DeepCopy() *ControlStatus {
	if in == nil {
		return nil
	}
	out := new(ControlStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvidenceContract) DeepCopyInto(out *EvidenceContract) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvidenceContract.
func (in *EvidenceContract) DeepCopy() *EvidenceContract {
	if in == nil {
		return nil
	}
	out := new(EvidenceContract)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EvidenceContract) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvidenceContractList) DeepCopyInto(out *EvidenceContractList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EvidenceContract, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvidenceContractList.
func (in *EvidenceContractList) DeepCopy() *EvidenceContractList {
	if in == nil {
		return nil
	}
	out := new(EvidenceContractList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EvidenceContractList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvidenceContractSpec) DeepCopyInto(out *EvidenceContractSpec) {
	*out = *in
	if in.Requirements != nil {
		in, out := &in.Requirements, &out.Requirements
		*out = make([]ContractRequirement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.OnMissingRequiredEvidence = in.OnMissingRequiredEvidence
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvidenceContractSpec.
func (in *EvidenceContractSpec) DeepCopy() *EvidenceContractSpec {
	if in == nil {
		return nil
	}
	out := new(EvidenceContractSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvidenceContractStatus) DeepCopyInto(out *EvidenceContractStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvidenceContractStatus.
func (in *EvidenceContractStatus) DeepCopy() *EvidenceContractStatus {
	if in == nil {
		return nil
	}
	out := new(EvidenceContractStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExceptionAuthority) DeepCopyInto(out *ExceptionAuthority) {
	*out = *in
	if in.RequiredApprovers != nil {
		in, out := &in.RequiredApprovers, &out.RequiredApprovers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExceptionAuthority.
func (in *ExceptionAuthority) DeepCopy() *ExceptionAuthority {
	if in == nil {
		return nil
	}
	out := new(ExceptionAuthority)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExceptionJustification) DeepCopyInto(out *ExceptionJustification) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExceptionJustification.
func (in *ExceptionJustification) DeepCopy() *ExceptionJustification {
	if in == nil {
		return nil
	}
	out := new(ExceptionJustification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExceptionSubjectRef) DeepCopyInto(out *ExceptionSubjectRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExceptionSubjectRef.
func (in *ExceptionSubjectRef) DeepCopy() *ExceptionSubjectRef {
	if in == nil {
		return nil
	}
	out := new(ExceptionSubjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExceptionValidity) DeepCopyInto(out *ExceptionValidity) {
	*out = *in
	in.NotBefore.DeepCopyInto(&out.NotBefore)
	in.NotAfter.DeepCopyInto(&out.NotAfter)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExceptionValidity.
func (in *ExceptionValidity) DeepCopy() *ExceptionValidity {
	if in == nil {
		return nil
	}
	out := new(ExceptionValidity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrameworkMapping) DeepCopyInto(out *FrameworkMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrameworkMapping.
func (in *FrameworkMapping) DeepCopy() *FrameworkMapping {
	if in == nil {
		return nil
	}
	out := new(FrameworkMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImplementationBindingRef) DeepCopyInto(out *ImplementationBindingRef) {
	*out = *in
	out.Ref = in.Ref
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImplementationBindingRef.
func (in *ImplementationBindingRef) DeepCopy() *ImplementationBindingRef {
	if in == nil {
		return nil
	}
	out := new(ImplementationBindingRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImplementationTargetRef) DeepCopyInto(out *ImplementationTargetRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImplementationTargetRef.
func (in *ImplementationTargetRef) DeepCopy() *ImplementationTargetRef {
	if in == nil {
		return nil
	}
	out := new(ImplementationTargetRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MissingEvidencePolicy) DeepCopyInto(out *MissingEvidencePolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MissingEvidencePolicy.
func (in *MissingEvidencePolicy) DeepCopy() *MissingEvidencePolicy {
	if in == nil {
		return nil
	}
	out := new(MissingEvidencePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyBehaviorConfig) DeepCopyInto(out *PolicyBehaviorConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyBehaviorConfig.
func (in *PolicyBehaviorConfig) DeepCopy() *PolicyBehaviorConfig {
	if in == nil {
		return nil
	}
	out := new(PolicyBehaviorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyEnforcementConfig) DeepCopyInto(out *PolicyEnforcementConfig) {
	*out = *in
	out.Admission = in.Admission
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyEnforcementConfig.
func (in *PolicyEnforcementConfig) DeepCopy() *PolicyEnforcementConfig {
	if in == nil {
		return nil
	}
	out := new(PolicyEnforcementConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyEvidenceConfig) DeepCopyInto(out *PolicyEvidenceConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyEvidenceConfig.
func (in *PolicyEvidenceConfig) DeepCopy() *PolicyEvidenceConfig {
	if in == nil {
		return nil
	}
	out := new(PolicyEvidenceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyFreshnessConfig) DeepCopyInto(out *PolicyFreshnessConfig) {
	*out = *in
	out.MaxEvaluationAge = in.MaxEvaluationAge
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyFreshnessConfig.
func (in *PolicyFreshnessConfig) DeepCopy() *PolicyFreshnessConfig {
	if in == nil {
		return nil
	}
	out := new(PolicyFreshnessConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequirementBinding) DeepCopyInto(out *RequirementBinding) {
	*out = *in
	if in.Implementations != nil {
		in, out := &in.Implementations, &out.Implementations
		*out = make([]ImplementationBindingRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequirementBinding.
func (in *RequirementBinding) DeepCopy() *RequirementBinding {
	if in == nil {
		return nil
	}
	out := new(RequirementBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StateEpoch) DeepCopyInto(out *StateEpoch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StateEpoch.
func (in *StateEpoch) DeepCopy() *StateEpoch {
	if in == nil {
		return nil
	}
	out := new(StateEpoch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StateSubjectRef) DeepCopyInto(out *StateSubjectRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StateSubjectRef.
func (in *StateSubjectRef) DeepCopy() *StateSubjectRef {
	if in == nil {
		return nil
	}
	out := new(StateSubjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubjectSelector) DeepCopyInto(out *SubjectSelector) {
	*out = *in
	if in.APIGroups != nil {
		in, out := &in.APIGroups, &out.APIGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Kinds != nil {
		in, out := &in.Kinds, &out.Kinds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubjectSelector.
func (in *SubjectSelector) DeepCopy() *SubjectSelector {
	if in == nil {
		return nil
	}
	out := new(SubjectSelector)
	in.DeepCopyInto(out)
	return out
}
