// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: assurance/common/v1/common.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AssuranceState represents canonical lifecycle states.
type AssuranceState int32

const (
	AssuranceState_ASSURANCE_STATE_UNSPECIFIED AssuranceState = 0
	AssuranceState_ASSURANCE_STATE_UNKNOWN     AssuranceState = 1
	AssuranceState_ASSURANCE_STATE_OBSERVED    AssuranceState = 2
	AssuranceState_ASSURANCE_STATE_VERIFIED    AssuranceState = 3
	AssuranceState_ASSURANCE_STATE_ASSURED     AssuranceState = 4
	AssuranceState_ASSURANCE_STATE_STALE       AssuranceState = 5
	AssuranceState_ASSURANCE_STATE_FAILED      AssuranceState = 6
)

// Enum value maps for AssuranceState.
var (
	AssuranceState_name = map[int32]string{
		0: "ASSURANCE_STATE_UNSPECIFIED",
		1: "ASSURANCE_STATE_UNKNOWN",
		2: "ASSURANCE_STATE_OBSERVED",
		3: "ASSURANCE_STATE_VERIFIED",
		4: "ASSURANCE_STATE_ASSURED",
		5: "ASSURANCE_STATE_STALE",
		6: "ASSURANCE_STATE_FAILED",
	}
	AssuranceState_value = map[string]int32{
		"ASSURANCE_STATE_UNSPECIFIED": 0,
		"ASSURANCE_STATE_UNKNOWN":     1,
		"ASSURANCE_STATE_OBSERVED":    2,
		"ASSURANCE_STATE_VERIFIED":    3,
		"ASSURANCE_STATE_ASSURED":     4,
		"ASSURANCE_STATE_STALE":       5,
		"ASSURANCE_STATE_FAILED":      6,
	}
)

func (x AssuranceState) Enum() *AssuranceState {
	p := new(AssuranceState)
	*p = x
	return p
}

func (x AssuranceState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssuranceState) Descriptor() protoreflect.EnumDescriptor {
	return file_assurance_common_v1_common_proto_enumTypes[0].Descriptor()
}

func (AssuranceState) Type() protoreflect.EnumType {
	return &file_assurance_common_v1_common_proto_enumTypes[0]
}

func (x AssuranceState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssuranceState.Descriptor instead.
func (AssuranceState) EnumDescriptor() ([]byte, []int) {
	return file_assurance_common_v1_common_proto_rawDescGZIP(), []int{0}
}

// Valence describes the directional effect of evidence.
type Valence int32

const (
	Valence_VALENCE_UNSPECIFIED Valence = 0
	Valence_VALENCE_POSITIVE    Valence = 1
	Valence_VALENCE_NEGATIVE    Valence = 2
	Valence_VALENCE_NEUTRAL     Valence = 3
	Valence_VALENCE_MIXED       Valence = 4
	Valence_VALENCE_UNRESOLVED  Valence = 5
)

// Enum value maps for Valence.
var (
	Valence_name = map[int32]string{
		0: "VALENCE_UNSPECIFIED",
		1: "VALENCE_POSITIVE",
		2: "VALENCE_NEGATIVE",
		3: "VALENCE_NEUTRAL",
		4: "VALENCE_MIXED",
		5: "VALENCE_UNRESOLVED",
	}
	Valence_value = map[string]int32{
		"VALENCE_UNSPECIFIED": 0,
		"VALENCE_POSITIVE":    1,
		"VALENCE_NEGATIVE":    2,
		"VALENCE_NEUTRAL":     3,
		"VALENCE_MIXED":       4,
		"VALENCE_UNRESOLVED":  5,
	}
)

func (x Valence) Enum() *Valence {
	p := new(Valence)
	*p = x
	return p
}

func (x Valence) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Valence) Descriptor() protoreflect.EnumDescriptor {
	return file_assurance_common_v1_common_proto_enumTypes[1].Descriptor()
}

func (Valence) Type() protoreflect.EnumType {
	return &file_assurance_common_v1_common_proto_enumTypes[1]
}

func (x Valence) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Valence.Descriptor instead.
func (Valence) EnumDescriptor() ([]byte, []int) {
	return file_assurance_common_v1_common_proto_rawDescGZIP(), []int{1}
}

// Coherence describes whether representations form one trustworthy state.
type Coherence int32

const (
	Coherence_COHERENCE_UNSPECIFIED        Coherence = 0
	Coherence_COHERENCE_COHERENT           Coherence = 1
	Coherence_COHERENCE_PARTIALLY_COHERENT Coherence = 2
	Coherence_COHERENCE_DECOHERENT         Coherence = 3
	Coherence_COHERENCE_RECONCILING        Coherence = 4
)

// Enum value maps for Coherence.
var (
	Coherence_name = map[int32]string{
		0: "COHERENCE_UNSPECIFIED",
		1: "COHERENCE_COHERENT",
		2: "COHERENCE_PARTIALLY_COHERENT",
		3: "COHERENCE_DECOHERENT",
		4: "COHERENCE_RECONCILING",
	}
	Coherence_value = map[string]int32{
		"COHERENCE_UNSPECIFIED":        0,
		"COHERENCE_COHERENT":           1,
		"COHERENCE_PARTIALLY_COHERENT": 2,
		"COHERENCE_DECOHERENT":         3,
		"COHERENCE_RECONCILING":        4,
	}
)

func (x Coherence) Enum() *Coherence {
	p := new(Coherence)
	*p = x
	return p
}

func (x Coherence) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Coherence) Descriptor() protoreflect.EnumDescriptor {
	return file_assurance_common_v1_common_proto_enumTypes[2].Descriptor()
}

func (Coherence) Type() protoreflect.EnumType {
	return &file_assurance_common_v1_common_proto_enumTypes[2]
}

func (x Coherence) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Coherence.Descriptor instead.
func (Coherence) EnumDescriptor() ([]byte, []int) {
	return file_assurance_common_v1_common_proto_rawDescGZIP(), []int{2}
}

// SubjectRef uniquely and stably addresses an evaluated entity.
type SubjectRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scheme        string                 `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectRef) Reset() {
	*x = SubjectRef{}
	mi := &file_assurance_common_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectRef) ProtoMessage() {}

func (x *SubjectRef) ProtoReflect() protoreflect.Message {
	mi := &file_assurance_common_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectRef.ProtoReflect.Descriptor instead.
func (*SubjectRef) Descriptor() ([]byte, []int) {
	return file_assurance_common_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *SubjectRef) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *SubjectRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SubjectRef) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// AuthorityRef identifies the authority backing an assertion or signature.
type AuthorityRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scheme        string                 `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	TrustDomain   string                 `protobuf:"bytes,3,opt,name=trust_domain,json=trustDomain,proto3" json:"trust_domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorityRef) Reset() {
	*x = AuthorityRef{}
	mi := &file_assurance_common_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorityRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorityRef) ProtoMessage() {}

func (x *AuthorityRef) ProtoReflect() protoreflect.Message {
	mi := &file_assurance_common_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorityRef.ProtoReflect.Descriptor instead.
func (*AuthorityRef) Descriptor() ([]byte, []int) {
	return file_assurance_common_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorityRef) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *AuthorityRef) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *AuthorityRef) GetTrustDomain() string {
	if x != nil {
		return x.TrustDomain
	}
	return ""
}

// AssuranceEpoch encapsulates the cryptographic state vector of the environment.
type AssuranceEpoch struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SubjectDigest        string                 `protobuf:"bytes,1,opt,name=subject_digest,json=subjectDigest,proto3" json:"subject_digest,omitempty"`
	ImplementationDigest string                 `protobuf:"bytes,2,opt,name=implementation_digest,json=implementationDigest,proto3" json:"implementation_digest,omitempty"`
	PolicyDigest         string                 `protobuf:"bytes,3,opt,name=policy_digest,json=policyDigest,proto3" json:"policy_digest,omitempty"`
	AuthorityDigest      string                 `protobuf:"bytes,4,opt,name=authority_digest,json=authorityDigest,proto3" json:"authority_digest,omitempty"`
	EnvironmentDigest    string                 `protobuf:"bytes,5,opt,name=environment_digest,json=environmentDigest,proto3" json:"environment_digest,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AssuranceEpoch) Reset() {
	*x = AssuranceEpoch{}
	mi := &file_assurance_common_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssuranceEpoch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssuranceEpoch) ProtoMessage() {}

func (x *AssuranceEpoch) ProtoReflect() protoreflect.Message {
	mi := &file_assurance_common_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssuranceEpoch.ProtoReflect.Descriptor instead.
func (*AssuranceEpoch) Descriptor() ([]byte, []int) {
	return file_assurance_common_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *AssuranceEpoch) GetSubjectDigest() string {
	if x != nil {
		return x.SubjectDigest
	}
	return ""
}

func (x *AssuranceEpoch) GetImplementationDigest() string {
	if x != nil {
		return x.ImplementationDigest
	}
	return ""
}

func (x *AssuranceEpoch) GetPolicyDigest() string {
	if x != nil {
		return x.PolicyDigest
	}
	return ""
}

func (x *AssuranceEpoch) GetAuthorityDigest() string {
	if x != nil {
		return x.AuthorityDigest
	}
	return ""
}

func (x *AssuranceEpoch) GetEnvironmentDigest() string {
	if x != nil {
		return x.EnvironmentDigest
	}
	return ""
}

// AssuranceVector models continuous multidimensional state.
type AssuranceVector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applicability Valence                `protobuf:"varint,1,opt,name=applicability,proto3,enum=ckodex.assurance.common.v1.Valence" json:"applicability,omitempty"`
	Conformance   Valence                `protobuf:"varint,2,opt,name=conformance,proto3,enum=ckodex.assurance.common.v1.Valence" json:"conformance,omitempty"`
	Provenance    Valence                `protobuf:"varint,3,opt,name=provenance,proto3,enum=ckodex.assurance.common.v1.Valence" json:"provenance,omitempty"`
	Integrity     Valence                `protobuf:"varint,4,opt,name=integrity,proto3,enum=ckodex.assurance.common.v1.Valence" json:"integrity,omitempty"`
	Authority     Valence                `protobuf:"varint,5,opt,name=authority,proto3,enum=ckodex.assurance.common.v1.Valence" json:"authority,omitempty"`
	Identity      Valence                `protobuf:"varint,6,opt,name=identity,proto3,enum=ckodex.assurance.common.v1.Valence" json:"identity,omitempty"`
	Runtime       Valence                `protobuf:"varint,7,opt,name=runtime,proto3,enum=ckodex.assurance.common.v1.Valence" json:"runtime,omitempty"`
	Freshness     Valence                `protobuf:"varint,8,opt,name=freshness,proto3,enum=ckodex.assurance.common.v1.Valence" json:"freshness,omitempty"`
	Completeness  Valence                `protobuf:"varint,9,opt,name=completeness,proto3,enum=ckodex.assurance.common.v1.Valence" json:"completeness,omitempty"`
	Coherence     Coherence              `protobuf:"varint,10,opt,name=coherence,proto3,enum=ckodex.assurance.common.v1.Coherence" json:"coherence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssuranceVector) Reset() {
	*x = AssuranceVector{}
	mi := &file_assurance_common_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssuranceVector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssuranceVector) ProtoMessage() {}

func (x *AssuranceVector) ProtoReflect() protoreflect.Message {
	mi := &file_assurance_common_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssuranceVector.ProtoReflect.Descriptor instead.
func (*AssuranceVector) Descriptor() ([]byte, []int) {
	return file_assurance_common_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *AssuranceVector) GetApplicability() Valence {
	if x != nil {
		return x.Applicability
	}
	return Valence_VALENCE_UNSPECIFIED
}

func (x *AssuranceVector) GetConformance() Valence {
	if x != nil {
		return x.Conformance
	}
	return Valence_VALENCE_UNSPECIFIED
}

func (x *AssuranceVector) GetProvenance() Valence {
	if x != nil {
		return x.Provenance
	}
	return Valence_VALENCE_UNSPECIFIED
}

func (x *AssuranceVector) GetIntegrity() Valence {
	if x != nil {
		return x.Integrity
	}
	return Valence_VALENCE_UNSPECIFIED
}

func (x *AssuranceVector) GetAuthority() Valence {
	if x != nil {
		return x.Authority
	}
	return Valence_VALENCE_UNSPECIFIED
}

func (x *AssuranceVector) GetIdentity() Valence {
	if x != nil {
		return x.Identity
	}
	return Valence_VALENCE_UNSPECIFIED
}

func (x *AssuranceVector) GetRuntime() Valence {
	if x != nil {
		return x.Runtime
	}
	return Valence_VALENCE_UNSPECIFIED
}

func (x *AssuranceVector) GetFreshness() Valence {
	if x != nil {
		return x.Freshness
	}
	return Valence_VALENCE_UNSPECIFIED
}

func (x *AssuranceVector) GetCompleteness() Valence {
	if x != nil {
		return x.Completeness
	}
	return Valence_VALENCE_UNSPECIFIED
}

func (x *AssuranceVector) GetCoherence() Coherence {
	if x != nil {
		return x.Coherence
	}
	return Coherence_COHERENCE_UNSPECIFIED
}

var File_assurance_common_v1_common_proto protoreflect.FileDescriptor

const file_assurance_common_v1_common_proto_rawDesc = "" +
	"\n" +
	" assurance/common/v1/common.proto\x12\x1ackodex.assurance.common.v1\"\xcb\x01\n" +
	"\n" +
	"SubjectRef\x12\x16\n" +
	"\x06scheme\x18\x01 \x01(\tR\x06scheme\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12V\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v26.ckodex.assurance.common.v1.SubjectRef.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"c\n" +
	"\fAuthorityRef\x12\x16\n" +
	"\x06scheme\x18\x01 \x01(\tR\x06scheme\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12!\n" +
	"\ftrust_domain\x18\x03 \x01(\tR\vtrustDomain\"\xeb\x01\n" +
	"\x0eAssuranceEpoch\x12%\n" +
	"\x0esubject_digest\x18\x01 \x01(\tR\rsubjectDigest\x123\n" +
	"\x15implementation_digest\x18\x02 \x01(\tR\x14implementationDigest\x12#\n" +
	"\rpolicy_digest\x18\x03 \x01(\tR\fpolicyDigest\x12)\n" +
	"\x10authority_digest\x18\x04 \x01(\tR\x0fauthorityDigest\x12-\n" +
	"\x12environment_digest\x18\x05 \x01(\tR\x11environmentDigest\"\xbf\x05\n" +
	"\x0fAssuranceVector\x12I\n" +
	"\rapplicability\x18\x01 \x01(\x0e2#.ckodex.assurance.common.v1.ValenceR\rapplicability\x12E\n" +
	"\vconformance\x18\x02 \x01(\x0e2#.ckodex.assurance.common.v1.ValenceR\vconformance\x12C\n" +
	"\n" +
	"provenance\x18\x03 \x01(\x0e2#.ckodex.assurance.common.v1.ValenceR\n" +
	"provenance\x12A\n" +
	"\tintegrity\x18\x04 \x01(\x0e2#.ckodex.assurance.common.v1.ValenceR\tintegrity\x12A\n" +
	"\tauthority\x18\x05 \x01(\x0e2#.ckodex.assurance.common.v1.ValenceR\tauthority\x12?\n" +
	"\bidentity\x18\x06 \x01(\x0e2#.ckodex.assurance.common.v1.ValenceR\bidentity\x12=\n" +
	"\aruntime\x18\a \x01(\x0e2#.ckodex.assurance.common.v1.ValenceR\aruntime\x12A\n" +
	"\tfreshness\x18\b \x01(\x0e2#.ckodex.assurance.common.v1.ValenceR\tfreshness\x12G\n" +
	"\fcompleteness\x18\t \x01(\x0e2#.ckodex.assurance.common.v1.ValenceR\fcompleteness\x12C\n" +
	"\tcoherence\x18\n" +
	" \x01(\x0e2%.ckodex.assurance.common.v1.CoherenceR\tcoherence*\xde\x01\n" +
	"\x0eAssuranceState\x12\x1f\n" +
	"\x1bASSURANCE_STATE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17ASSURANCE_STATE_UNKNOWN\x10\x01\x12\x1c\n" +
	"\x18ASSURANCE_STATE_OBSERVED\x10\x02\x12\x1c\n" +
	"\x18ASSURANCE_STATE_VERIFIED\x10\x03\x12\x1b\n" +
	"\x17ASSURANCE_STATE_ASSURED\x10\x04\x12\x19\n" +
	"\x15ASSURANCE_STATE_STALE\x10\x05\x12\x1a\n" +
	"\x16ASSURANCE_STATE_FAILED\x10\x06*\x8e\x01\n" +
	"\aValence\x12\x17\n" +
	"\x13VALENCE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10VALENCE_POSITIVE\x10\x01\x12\x14\n" +
	"\x10VALENCE_NEGATIVE\x10\x02\x12\x13\n" +
	"\x0fVALENCE_NEUTRAL\x10\x03\x12\x11\n" +
	"\rVALENCE_MIXED\x10\x04\x12\x16\n" +
	"\x12VALENCE_UNRESOLVED\x10\x05*\x95\x01\n" +
	"\tCoherence\x12\x19\n" +
	"\x15COHERENCE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12COHERENCE_COHERENT\x10\x01\x12 \n" +
	"\x1cCOHERENCE_PARTIALLY_COHERENT\x10\x02\x12\x18\n" +
	"\x14COHERENCE_DECOHERENT\x10\x03\x12\x19\n" +
	"\x15COHERENCE_RECONCILING\x10\x04BHZFgithub.com/ckodex-labs/ckodex-oskal/proto/assurance/common/v1;commonv1b\x06proto3"

var (
	file_assurance_common_v1_common_proto_rawDescOnce sync.Once
	file_assurance_common_v1_common_proto_rawDescData []byte
)

func file_assurance_common_v1_common_proto_rawDescGZIP() []byte {
	file_assurance_common_v1_common_proto_rawDescOnce.Do(func() {
		file_assurance_common_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_assurance_common_v1_common_proto_rawDesc), len(file_assurance_common_v1_common_proto_rawDesc)))
	})
	return file_assurance_common_v1_common_proto_rawDescData
}

var file_assurance_common_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_assurance_common_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_assurance_common_v1_common_proto_goTypes = []any{
	(AssuranceState)(0),     // 0: ckodex.assurance.common.v1.AssuranceState
	(Valence)(0),            // 1: ckodex.assurance.common.v1.Valence
	(Coherence)(0),          // 2: ckodex.assurance.common.v1.Coherence
	(*SubjectRef)(nil),      // 3: ckodex.assurance.common.v1.SubjectRef
	(*AuthorityRef)(nil),    // 4: ckodex.assurance.common.v1.AuthorityRef
	(*AssuranceEpoch)(nil),  // 5: ckodex.assurance.common.v1.AssuranceEpoch
	(*AssuranceVector)(nil), // 6: ckodex.assurance.common.v1.AssuranceVector
	nil,                     // 7: ckodex.assurance.common.v1.SubjectRef.AttributesEntry
}
var file_assurance_common_v1_common_proto_depIdxs = []int32{
	7,  // 0: ckodex.assurance.common.v1.SubjectRef.attributes:type_name -> ckodex.assurance.common.v1.SubjectRef.AttributesEntry
	1,  // 1: ckodex.assurance.common.v1.AssuranceVector.applicability:type_name -> ckodex.assurance.common.v1.Valence
	1,  // 2: ckodex.assurance.common.v1.AssuranceVector.conformance:type_name -> ckodex.assurance.common.v1.Valence
	1,  // 3: ckodex.assurance.common.v1.AssuranceVector.provenance:type_name -> ckodex.assurance.common.v1.Valence
	1,  // 4: ckodex.assurance.common.v1.AssuranceVector.integrity:type_name -> ckodex.assurance.common.v1.Valence
	1,  // 5: ckodex.assurance.common.v1.AssuranceVector.authority:type_name -> ckodex.assurance.common.v1.Valence
	1,  // 6: ckodex.assurance.common.v1.AssuranceVector.identity:type_name -> ckodex.assurance.common.v1.Valence
	1,  // 7: ckodex.assurance.common.v1.AssuranceVector.runtime:type_name -> ckodex.assurance.common.v1.Valence
	1,  // 8: ckodex.assurance.common.v1.AssuranceVector.freshness:type_name -> ckodex.assurance.common.v1.Valence
	1,  // 9: ckodex.assurance.common.v1.AssuranceVector.completeness:type_name -> ckodex.assurance.common.v1.Valence
	2,  // 10: ckodex.assurance.common.v1.AssuranceVector.coherence:type_name -> ckodex.assurance.common.v1.Coherence
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_assurance_common_v1_common_proto_init() }
func file_assurance_common_v1_common_proto_init() {
	if File_assurance_common_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_assurance_common_v1_common_proto_rawDesc), len(file_assurance_common_v1_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_assurance_common_v1_common_proto_goTypes,
		DependencyIndexes: file_assurance_common_v1_common_proto_depIdxs,
		EnumInfos:         file_assurance_common_v1_common_proto_enumTypes,
		MessageInfos:      file_assurance_common_v1_common_proto_msgTypes,
	}.Build()
	File_assurance_common_v1_common_proto = out.File
	file_assurance_common_v1_common_proto_goTypes = nil
	file_assurance_common_v1_common_proto_depIdxs = nil
}
