apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-api
  namespace: ckodex-assurance-test
  labels:
    app.kubernetes.io/name: payments-api
    app.kubernetes.io/part-of: payments-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: payments-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: payments-api
    spec:
      containers:
        - name: web
          image: registry.k8s.io/pause:3.9
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
            capabilities:
              drop:
                - ALL
