// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: assurance/evidence/v1/evidence.proto

package evidencev1

import (
	v1 "github.com/ckodex-labs/ckodex-oskal/proto/assurance/common/v1"
	v11 "github.com/ckodex-labs/ckodex-oskal/proto/assurance/control/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EvidenceRef points to an immutable content-addressed evidence artifact.
type EvidenceRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Digest        string                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	MediaType     string                 `protobuf:"bytes,3,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvidenceRef) Reset() {
	*x = EvidenceRef{}
	mi := &file_assurance_evidence_v1_evidence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidenceRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidenceRef) ProtoMessage() {}

func (x *EvidenceRef) ProtoReflect() protoreflect.Message {
	mi := &file_assurance_evidence_v1_evidence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidenceRef.ProtoReflect.Descriptor instead.
func (*EvidenceRef) Descriptor() ([]byte, []int) {
	return file_assurance_evidence_v1_evidence_proto_rawDescGZIP(), []int{0}
}

func (x *EvidenceRef) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *EvidenceRef) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *EvidenceRef) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

// Observation represents an atomic fact captured about a subject.
type Observation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Subject       *v1.SubjectRef         `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	ObservedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	Observer      *v1.AuthorityRef       `protobuf:"bytes,5,opt,name=observer,proto3" json:"observer,omitempty"`
	Evidence      []*EvidenceRef         `protobuf:"bytes,6,rep,name=evidence,proto3" json:"evidence,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,7,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Observation) Reset() {
	*x = Observation{}
	mi := &file_assurance_evidence_v1_evidence_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observation) ProtoMessage() {}

func (x *Observation) ProtoReflect() protoreflect.Message {
	mi := &file_assurance_evidence_v1_evidence_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observation.ProtoReflect.Descriptor instead.
func (*Observation) Descriptor() ([]byte, []int) {
	return file_assurance_evidence_v1_evidence_proto_rawDescGZIP(), []int{1}
}

func (x *Observation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Observation) GetSubject() *v1.SubjectRef {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *Observation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Observation) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *Observation) GetObserver() *v1.AuthorityRef {
	if x != nil {
		return x.Observer
	}
	return nil
}

func (x *Observation) GetEvidence() []*EvidenceRef {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *Observation) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// EvidenceRequirement specifies an individual required piece of evidence.
type EvidenceRequirement struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EvidenceType      string                 `protobuf:"bytes,2,opt,name=evidence_type,json=evidenceType,proto3" json:"evidence_type,omitempty"`
	Required          bool                   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	MaxAge            *durationpb.Duration   `protobuf:"bytes,4,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`
	AcceptedProducers []string               `protobuf:"bytes,5,rep,name=accepted_producers,json=acceptedProducers,proto3" json:"accepted_producers,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EvidenceRequirement) Reset() {
	*x = EvidenceRequirement{}
	mi := &file_assurance_evidence_v1_evidence_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidenceRequirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidenceRequirement) ProtoMessage() {}

func (x *EvidenceRequirement) ProtoReflect() protoreflect.Message {
	mi := &file_assurance_evidence_v1_evidence_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidenceRequirement.ProtoReflect.Descriptor instead.
func (*EvidenceRequirement) Descriptor() ([]byte, []int) {
	return file_assurance_evidence_v1_evidence_proto_rawDescGZIP(), []int{2}
}

func (x *EvidenceRequirement) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EvidenceRequirement) GetEvidenceType() string {
	if x != nil {
		return x.EvidenceType
	}
	return ""
}

func (x *EvidenceRequirement) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *EvidenceRequirement) GetMaxAge() *durationpb.Duration {
	if x != nil {
		return x.MaxAge
	}
	return nil
}

func (x *EvidenceRequirement) GetAcceptedProducers() []string {
	if x != nil {
		return x.AcceptedProducers
	}
	return nil
}

// EvidenceContract defines mandatory proof requirements for a control binding.
type EvidenceContract struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                   string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Requirements           []*EvidenceRequirement `protobuf:"bytes,3,rep,name=requirements,proto3" json:"requirements,omitempty"`
	OnMissingRequiredState v1.AssuranceState      `protobuf:"varint,4,opt,name=on_missing_required_state,json=onMissingRequiredState,proto3,enum=ckodex.assurance.common.v1.AssuranceState" json:"on_missing_required_state,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EvidenceContract) Reset() {
	*x = EvidenceContract{}
	mi := &file_assurance_evidence_v1_evidence_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidenceContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidenceContract) ProtoMessage() {}

func (x *EvidenceContract) ProtoReflect() protoreflect.Message {
	mi := &file_assurance_evidence_v1_evidence_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidenceContract.ProtoReflect.Descriptor instead.
func (*EvidenceContract) Descriptor() ([]byte, []int) {
	return file_assurance_evidence_v1_evidence_proto_rawDescGZIP(), []int{3}
}

func (x *EvidenceContract) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EvidenceContract) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EvidenceContract) GetRequirements() []*EvidenceRequirement {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *EvidenceContract) GetOnMissingRequiredState() v1.AssuranceState {
	if x != nil {
		return x.OnMissingRequiredState
	}
	return v1.AssuranceState(0)
}

// EvidenceEnvelope packages evidence metadata and cryptographic bindings.
type EvidenceEnvelope struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Schema          string                 `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	Id              string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Subject         *v1.SubjectRef         `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	ObservationType string                 `protobuf:"bytes,4,opt,name=observation_type,json=observationType,proto3" json:"observation_type,omitempty"`
	CapturedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=captured_at,json=capturedAt,proto3" json:"captured_at,omitempty"`
	Producer        *v1.AuthorityRef       `protobuf:"bytes,6,opt,name=producer,proto3" json:"producer,omitempty"`
	Artifact        *EvidenceRef           `protobuf:"bytes,7,opt,name=artifact,proto3" json:"artifact,omitempty"`
	IntegrityDigest string                 `protobuf:"bytes,8,opt,name=integrity_digest,json=integrityDigest,proto3" json:"integrity_digest,omitempty"`
	SignatureRef    string                 `protobuf:"bytes,9,opt,name=signature_ref,json=signatureRef,proto3" json:"signature_ref,omitempty"`
	Epoch           *v1.AssuranceEpoch     `protobuf:"bytes,10,opt,name=epoch,proto3" json:"epoch,omitempty"`
	ControlRefs     []*v11.ControlRef      `protobuf:"bytes,11,rep,name=control_refs,json=controlRefs,proto3" json:"control_refs,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EvidenceEnvelope) Reset() {
	*x = EvidenceEnvelope{}
	mi := &file_assurance_evidence_v1_evidence_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidenceEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidenceEnvelope) ProtoMessage() {}

func (x *EvidenceEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_assurance_evidence_v1_evidence_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidenceEnvelope.ProtoReflect.Descriptor instead.
func (*EvidenceEnvelope) Descriptor() ([]byte, []int) {
	return file_assurance_evidence_v1_evidence_proto_rawDescGZIP(), []int{4}
}

func (x *EvidenceEnvelope) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *EvidenceEnvelope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EvidenceEnvelope) GetSubject() *v1.SubjectRef {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *EvidenceEnvelope) GetObservationType() string {
	if x != nil {
		return x.ObservationType
	}
	return ""
}

func (x *EvidenceEnvelope) GetCapturedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CapturedAt
	}
	return nil
}

func (x *EvidenceEnvelope) GetProducer() *v1.AuthorityRef {
	if x != nil {
		return x.Producer
	}
	return nil
}

func (x *EvidenceEnvelope) GetArtifact() *EvidenceRef {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *EvidenceEnvelope) GetIntegrityDigest() string {
	if x != nil {
		return x.IntegrityDigest
	}
	return ""
}

func (x *EvidenceEnvelope) GetSignatureRef() string {
	if x != nil {
		return x.SignatureRef
	}
	return ""
}

func (x *EvidenceEnvelope) GetEpoch() *v1.AssuranceEpoch {
	if x != nil {
		return x.Epoch
	}
	return nil
}

func (x *EvidenceEnvelope) GetControlRefs() []*v11.ControlRef {
	if x != nil {
		return x.ControlRefs
	}
	return nil
}

// EvidenceCompleteness tracks coverage of required evidence.
type EvidenceCompleteness struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Required      int32                  `protobuf:"varint,1,opt,name=required,proto3" json:"required,omitempty"`
	Present       int32                  `protobuf:"varint,2,opt,name=present,proto3" json:"present,omitempty"`
	Verified      int32                  `protobuf:"varint,3,opt,name=verified,proto3" json:"verified,omitempty"`
	Stale         int32                  `protobuf:"varint,4,opt,name=stale,proto3" json:"stale,omitempty"`
	Missing       int32                  `protobuf:"varint,5,opt,name=missing,proto3" json:"missing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvidenceCompleteness) Reset() {
	*x = EvidenceCompleteness{}
	mi := &file_assurance_evidence_v1_evidence_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidenceCompleteness) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidenceCompleteness) ProtoMessage() {}

func (x *EvidenceCompleteness) ProtoReflect() protoreflect.Message {
	mi := &file_assurance_evidence_v1_evidence_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidenceCompleteness.ProtoReflect.Descriptor instead.
func (*EvidenceCompleteness) Descriptor() ([]byte, []int) {
	return file_assurance_evidence_v1_evidence_proto_rawDescGZIP(), []int{5}
}

func (x *EvidenceCompleteness) GetRequired() int32 {
	if x != nil {
		return x.Required
	}
	return 0
}

func (x *EvidenceCompleteness) GetPresent() int32 {
	if x != nil {
		return x.Present
	}
	return 0
}

func (x *EvidenceCompleteness) GetVerified() int32 {
	if x != nil {
		return x.Verified
	}
	return 0
}

func (x *EvidenceCompleteness) GetStale() int32 {
	if x != nil {
		return x.Stale
	}
	return 0
}

func (x *EvidenceCompleteness) GetMissing() int32 {
	if x != nil {
		return x.Missing
	}
	return 0
}

var File_assurance_evidence_v1_evidence_proto protoreflect.FileDescriptor

const file_assurance_evidence_v1_evidence_proto_rawDesc = "" +
	"\n" +
	"$assurance/evidence/v1/evidence.proto\x12\x1cckodex.assurance.evidence.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a assurance/common/v1/common.proto\x1a\"assurance/control/v1/control.proto\"V\n" +
	"\vEvidenceRef\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\x12\x1d\n" +
	"\n" +
	"media_type\x18\x03 \x01(\tR\tmediaType\"\xd7\x03\n" +
	"\vObservation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12@\n" +
	"\asubject\x18\x02 \x01(\v2&.ckodex.assurance.common.v1.SubjectRefR\asubject\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12;\n" +
	"\vobserved_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12D\n" +
	"\bobserver\x18\x05 \x01(\v2(.ckodex.assurance.common.v1.AuthorityRefR\bobserver\x12E\n" +
	"\bevidence\x18\x06 \x03(\v2).ckodex.assurance.evidence.v1.EvidenceRefR\bevidence\x12Y\n" +
	"\n" +
	"attributes\x18\a \x03(\v29.ckodex.assurance.evidence.v1.Observation.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc9\x01\n" +
	"\x13EvidenceRequirement\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\revidence_type\x18\x02 \x01(\tR\fevidenceType\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\x122\n" +
	"\amax_age\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x06maxAge\x12-\n" +
	"\x12accepted_producers\x18\x05 \x03(\tR\x11acceptedProducers\"\xf4\x01\n" +
	"\x10EvidenceContract\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12U\n" +
	"\frequirements\x18\x03 \x03(\v21.ckodex.assurance.evidence.v1.EvidenceRequirementR\frequirements\x12e\n" +
	"\x19on_missing_required_state\x18\x04 \x01(\x0e2*.ckodex.assurance.common.v1.AssuranceStateR\x16onMissingRequiredState\"\xcf\x04\n" +
	"\x10EvidenceEnvelope\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\tR\x06schema\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12@\n" +
	"\asubject\x18\x03 \x01(\v2&.ckodex.assurance.common.v1.SubjectRefR\asubject\x12)\n" +
	"\x10observation_type\x18\x04 \x01(\tR\x0fobservationType\x12;\n" +
	"\vcaptured_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"capturedAt\x12D\n" +
	"\bproducer\x18\x06 \x01(\v2(.ckodex.assurance.common.v1.AuthorityRefR\bproducer\x12E\n" +
	"\bartifact\x18\a \x01(\v2).ckodex.assurance.evidence.v1.EvidenceRefR\bartifact\x12)\n" +
	"\x10integrity_digest\x18\b \x01(\tR\x0fintegrityDigest\x12#\n" +
	"\rsignature_ref\x18\t \x01(\tR\fsignatureRef\x12@\n" +
	"\x05epoch\x18\n" +
	" \x01(\v2*.ckodex.assurance.common.v1.AssuranceEpochR\x05epoch\x12J\n" +
	"\fcontrol_refs\x18\v \x03(\v2'.ckodex.assurance.control.v1.ControlRefR\vcontrolRefs\"\x98\x01\n" +
	"\x14EvidenceCompleteness\x12\x1a\n" +
	"\brequired\x18\x01 \x01(\x05R\brequired\x12\x18\n" +
	"\apresent\x18\x02 \x01(\x05R\apresent\x12\x1a\n" +
	"\bverified\x18\x03 \x01(\x05R\bverified\x12\x14\n" +
	"\x05stale\x18\x04 \x01(\x05R\x05stale\x12\x18\n" +
	"\amissing\x18\x05 \x01(\x05R\amissingBLZJgithub.com/ckodex-labs/ckodex-oskal/proto/assurance/evidence/v1;evidencev1b\x06proto3"

var (
	file_assurance_evidence_v1_evidence_proto_rawDescOnce sync.Once
	file_assurance_evidence_v1_evidence_proto_rawDescData []byte
)

func file_assurance_evidence_v1_evidence_proto_rawDescGZIP() []byte {
	file_assurance_evidence_v1_evidence_proto_rawDescOnce.Do(func() {
		file_assurance_evidence_v1_evidence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_assurance_evidence_v1_evidence_proto_rawDesc), len(file_assurance_evidence_v1_evidence_proto_rawDesc)))
	})
	return file_assurance_evidence_v1_evidence_proto_rawDescData
}

var file_assurance_evidence_v1_evidence_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_assurance_evidence_v1_evidence_proto_goTypes = []any{
	(*EvidenceRef)(nil),           // 0: ckodex.assurance.evidence.v1.EvidenceRef
	(*Observation)(nil),           // 1: ckodex.assurance.evidence.v1.Observation
	(*EvidenceRequirement)(nil),   // 2: ckodex.assurance.evidence.v1.EvidenceRequirement
	(*EvidenceContract)(nil),      // 3: ckodex.assurance.evidence.v1.EvidenceContract
	(*EvidenceEnvelope)(nil),      // 4: ckodex.assurance.evidence.v1.EvidenceEnvelope
	(*EvidenceCompleteness)(nil),  // 5: ckodex.assurance.evidence.v1.EvidenceCompleteness
	nil,                           // 6: ckodex.assurance.evidence.v1.Observation.AttributesEntry
	(*v1.SubjectRef)(nil),         // 7: ckodex.assurance.common.v1.SubjectRef
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
	(*v1.AuthorityRef)(nil),       // 9: ckodex.assurance.common.v1.AuthorityRef
	(*durationpb.Duration)(nil),   // 10: google.protobuf.Duration
	(v1.AssuranceState)(0),        // 11: ckodex.assurance.common.v1.AssuranceState
	(*v1.AssuranceEpoch)(nil),     // 12: ckodex.assurance.common.v1.AssuranceEpoch
	(*v11.ControlRef)(nil),        // 13: ckodex.assurance.control.v1.ControlRef
}
var file_assurance_evidence_v1_evidence_proto_depIdxs = []int32{
	7,  // 0: ckodex.assurance.evidence.v1.Observation.subject:type_name -> ckodex.assurance.common.v1.SubjectRef
	8,  // 1: ckodex.assurance.evidence.v1.Observation.observed_at:type_name -> google.protobuf.Timestamp
	9,  // 2: ckodex.assurance.evidence.v1.Observation.observer:type_name -> ckodex.assurance.common.v1.AuthorityRef
	0,  // 3: ckodex.assurance.evidence.v1.Observation.evidence:type_name -> ckodex.assurance.evidence.v1.EvidenceRef
	6,  // 4: ckodex.assurance.evidence.v1.Observation.attributes:type_name -> ckodex.assurance.evidence.v1.Observation.AttributesEntry
	10, // 5: ckodex.assurance.evidence.v1.EvidenceRequirement.max_age:type_name -> google.protobuf.Duration
	2,  // 6: ckodex.assurance.evidence.v1.EvidenceContract.requirements:type_name -> ckodex.assurance.evidence.v1.EvidenceRequirement
	11, // 7: ckodex.assurance.evidence.v1.EvidenceContract.on_missing_required_state:type_name -> ckodex.assurance.common.v1.AssuranceState
	7,  // 8: ckodex.assurance.evidence.v1.EvidenceEnvelope.subject:type_name -> ckodex.assurance.common.v1.SubjectRef
	8,  // 9: ckodex.assurance.evidence.v1.EvidenceEnvelope.captured_at:type_name -> google.protobuf.Timestamp
	9,  // 10: ckodex.assurance.evidence.v1.EvidenceEnvelope.producer:type_name -> ckodex.assurance.common.v1.AuthorityRef
	0,  // 11: ckodex.assurance.evidence.v1.EvidenceEnvelope.artifact:type_name -> ckodex.assurance.evidence.v1.EvidenceRef
	12, // 12: ckodex.assurance.evidence.v1.EvidenceEnvelope.epoch:type_name -> ckodex.assurance.common.v1.AssuranceEpoch
	13, // 13: ckodex.assurance.evidence.v1.EvidenceEnvelope.control_refs:type_name -> ckodex.assurance.control.v1.ControlRef
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_assurance_evidence_v1_evidence_proto_init() }
func file_assurance_evidence_v1_evidence_proto_init() {
	if File_assurance_evidence_v1_evidence_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_assurance_evidence_v1_evidence_proto_rawDesc), len(file_assurance_evidence_v1_evidence_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_assurance_evidence_v1_evidence_proto_goTypes,
		DependencyIndexes: file_assurance_evidence_v1_evidence_proto_depIdxs,
		MessageInfos:      file_assurance_evidence_v1_evidence_proto_msgTypes,
	}.Build()
	File_assurance_evidence_v1_evidence_proto = out.File
	file_assurance_evidence_v1_evidence_proto_goTypes = nil
	file_assurance_evidence_v1_evidence_proto_depIdxs = nil
}
