// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: assurance/control/v1/control.proto

package controlv1

import (
	v1 "github.com/ckodex-labs/oskal/proto/assurance/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ImplementationPurpose defines control realization purpose.
type ImplementationPurpose int32

const (
	ImplementationPurpose_IMPLEMENTATION_PURPOSE_UNSPECIFIED   ImplementationPurpose = 0
	ImplementationPurpose_IMPLEMENTATION_PURPOSE_PREVENTIVE    ImplementationPurpose = 1
	ImplementationPurpose_IMPLEMENTATION_PURPOSE_DETECTIVE     ImplementationPurpose = 2
	ImplementationPurpose_IMPLEMENTATION_PURPOSE_CORRECTIVE    ImplementationPurpose = 3
	ImplementationPurpose_IMPLEMENTATION_PURPOSE_COMPENSATING  ImplementationPurpose = 4
	ImplementationPurpose_IMPLEMENTATION_PURPOSE_INFORMATIONAL ImplementationPurpose = 5
)

// Enum value maps for ImplementationPurpose.
var (
	ImplementationPurpose_name = map[int32]string{
		0: "IMPLEMENTATION_PURPOSE_UNSPECIFIED",
		1: "IMPLEMENTATION_PURPOSE_PREVENTIVE",
		2: "IMPLEMENTATION_PURPOSE_DETECTIVE",
		3: "IMPLEMENTATION_PURPOSE_CORRECTIVE",
		4: "IMPLEMENTATION_PURPOSE_COMPENSATING",
		5: "IMPLEMENTATION_PURPOSE_INFORMATIONAL",
	}
	ImplementationPurpose_value = map[string]int32{
		"IMPLEMENTATION_PURPOSE_UNSPECIFIED":   0,
		"IMPLEMENTATION_PURPOSE_PREVENTIVE":    1,
		"IMPLEMENTATION_PURPOSE_DETECTIVE":     2,
		"IMPLEMENTATION_PURPOSE_CORRECTIVE":    3,
		"IMPLEMENTATION_PURPOSE_COMPENSATING":  4,
		"IMPLEMENTATION_PURPOSE_INFORMATIONAL": 5,
	}
)

func (x ImplementationPurpose) Enum() *ImplementationPurpose {
	p := new(ImplementationPurpose)
	*p = x
	return p
}

func (x ImplementationPurpose) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImplementationPurpose) Descriptor() protoreflect.EnumDescriptor {
	return file_assurance_control_v1_control_proto_enumTypes[0].Descriptor()
}

func (ImplementationPurpose) Type() protoreflect.EnumType {
	return &file_assurance_control_v1_control_proto_enumTypes[0]
}

func (x ImplementationPurpose) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImplementationPurpose.Descriptor instead.
func (ImplementationPurpose) EnumDescriptor() ([]byte, []int) {
	return file_assurance_control_v1_control_proto_rawDescGZIP(), []int{0}
}

// ControlRef identifies a standard or canonical security control.
type ControlRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlRef) Reset() {
	*x = ControlRef{}
	mi := &file_assurance_control_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlRef) ProtoMessage() {}

func (x *ControlRef) ProtoReflect() protoreflect.Message {
	mi := &file_assurance_control_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlRef.ProtoReflect.Descriptor instead.
func (*ControlRef) Descriptor() ([]byte, []int) {
	return file_assurance_control_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *ControlRef) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ControlRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ControlRef) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// ImplementationRef identifies a realization mechanism.
type ImplementationRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Digest        string                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	Purpose       ImplementationPurpose  `protobuf:"varint,4,opt,name=purpose,proto3,enum=ckodex.assurance.control.v1.ImplementationPurpose" json:"purpose,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImplementationRef) Reset() {
	*x = ImplementationRef{}
	mi := &file_assurance_control_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImplementationRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImplementationRef) ProtoMessage() {}

func (x *ImplementationRef) ProtoReflect() protoreflect.Message {
	mi := &file_assurance_control_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImplementationRef.ProtoReflect.Descriptor instead.
func (*ImplementationRef) Descriptor() ([]byte, []int) {
	return file_assurance_control_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *ImplementationRef) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ImplementationRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImplementationRef) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *ImplementationRef) GetPurpose() ImplementationPurpose {
	if x != nil {
		return x.Purpose
	}
	return ImplementationPurpose_IMPLEMENTATION_PURPOSE_UNSPECIFIED
}

// AtomicControl represents an individually evaluable decomposed control atom.
type AtomicControl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Satisfied     bool                   `protobuf:"varint,3,opt,name=satisfied,proto3" json:"satisfied,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AtomicControl) Reset() {
	*x = AtomicControl{}
	mi := &file_assurance_control_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtomicControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtomicControl) ProtoMessage() {}

func (x *AtomicControl) ProtoReflect() protoreflect.Message {
	mi := &file_assurance_control_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtomicControl.ProtoReflect.Descriptor instead.
func (*AtomicControl) Descriptor() ([]byte, []int) {
	return file_assurance_control_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *AtomicControl) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AtomicControl) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AtomicControl) GetSatisfied() bool {
	if x != nil {
		return x.Satisfied
	}
	return false
}

// ImplementationBinding binds controls, subjects, and implementation providers.
type ImplementationBinding struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Controls             []*ControlRef          `protobuf:"bytes,2,rep,name=controls,proto3" json:"controls,omitempty"`
	Subjects             []*v1.SubjectRef       `protobuf:"bytes,3,rep,name=subjects,proto3" json:"subjects,omitempty"`
	Implementations      []*ImplementationRef   `protobuf:"bytes,4,rep,name=implementations,proto3" json:"implementations,omitempty"`
	EvidenceContractRefs []string               `protobuf:"bytes,5,rep,name=evidence_contract_refs,json=evidenceContractRefs,proto3" json:"evidence_contract_refs,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ImplementationBinding) Reset() {
	*x = ImplementationBinding{}
	mi := &file_assurance_control_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImplementationBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImplementationBinding) ProtoMessage() {}

func (x *ImplementationBinding) ProtoReflect() protoreflect.Message {
	mi := &file_assurance_control_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImplementationBinding.ProtoReflect.Descriptor instead.
func (*ImplementationBinding) Descriptor() ([]byte, []int) {
	return file_assurance_control_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *ImplementationBinding) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImplementationBinding) GetControls() []*ControlRef {
	if x != nil {
		return x.Controls
	}
	return nil
}

func (x *ImplementationBinding) GetSubjects() []*v1.SubjectRef {
	if x != nil {
		return x.Subjects
	}
	return nil
}

func (x *ImplementationBinding) GetImplementations() []*ImplementationRef {
	if x != nil {
		return x.Implementations
	}
	return nil
}

func (x *ImplementationBinding) GetEvidenceContractRefs() []string {
	if x != nil {
		return x.EvidenceContractRefs
	}
	return nil
}

var File_assurance_control_v1_control_proto protoreflect.FileDescriptor

const file_assurance_control_v1_control_proto_rawDesc = "" +
	"\n" +
	"\"assurance/control/v1/control.proto\x12\x1bckodex.assurance.control.v1\x1a assurance/common/v1/common.proto\"T\n" +
	"\n" +
	"ControlRef\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\xa5\x01\n" +
	"\x11ImplementationRef\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\tR\x06digest\x12L\n" +
	"\apurpose\x18\x04 \x01(\x0e22.ckodex.assurance.control.v1.ImplementationPurposeR\apurpose\"_\n" +
	"\rAtomicControl\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1c\n" +
	"\tsatisfied\x18\x03 \x01(\bR\tsatisfied\"\xc0\x02\n" +
	"\x15ImplementationBinding\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12C\n" +
	"\bcontrols\x18\x02 \x03(\v2'.ckodex.assurance.control.v1.ControlRefR\bcontrols\x12B\n" +
	"\bsubjects\x18\x03 \x03(\v2&.ckodex.assurance.common.v1.SubjectRefR\bsubjects\x12X\n" +
	"\x0fimplementations\x18\x04 \x03(\v2..ckodex.assurance.control.v1.ImplementationRefR\x0fimplementations\x124\n" +
	"\x16evidence_contract_refs\x18\x05 \x03(\tR\x14evidenceContractRefs*\x86\x02\n" +
	"\x15ImplementationPurpose\x12&\n" +
	"\"IMPLEMENTATION_PURPOSE_UNSPECIFIED\x10\x00\x12%\n" +
	"!IMPLEMENTATION_PURPOSE_PREVENTIVE\x10\x01\x12$\n" +
	" IMPLEMENTATION_PURPOSE_DETECTIVE\x10\x02\x12%\n" +
	"!IMPLEMENTATION_PURPOSE_CORRECTIVE\x10\x03\x12'\n" +
	"#IMPLEMENTATION_PURPOSE_COMPENSATING\x10\x04\x12(\n" +
	"$IMPLEMENTATION_PURPOSE_INFORMATIONAL\x10\x05BCZAgithub.com/ckodex-labs/oskal/proto/assurance/control/v1;controlv1b\x06proto3"

var (
	file_assurance_control_v1_control_proto_rawDescOnce sync.Once
	file_assurance_control_v1_control_proto_rawDescData []byte
)

func file_assurance_control_v1_control_proto_rawDescGZIP() []byte {
	file_assurance_control_v1_control_proto_rawDescOnce.Do(func() {
		file_assurance_control_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_assurance_control_v1_control_proto_rawDesc), len(file_assurance_control_v1_control_proto_rawDesc)))
	})
	return file_assurance_control_v1_control_proto_rawDescData
}

var file_assurance_control_v1_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_assurance_control_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_assurance_control_v1_control_proto_goTypes = []any{
	(ImplementationPurpose)(0),    // 0: ckodex.assurance.control.v1.ImplementationPurpose
	(*ControlRef)(nil),            // 1: ckodex.assurance.control.v1.ControlRef
	(*ImplementationRef)(nil),     // 2: ckodex.assurance.control.v1.ImplementationRef
	(*AtomicControl)(nil),         // 3: ckodex.assurance.control.v1.AtomicControl
	(*ImplementationBinding)(nil), // 4: ckodex.assurance.control.v1.ImplementationBinding
	(*v1.SubjectRef)(nil),         // 5: ckodex.assurance.common.v1.SubjectRef
}
var file_assurance_control_v1_control_proto_depIdxs = []int32{
	0, // 0: ckodex.assurance.control.v1.ImplementationRef.purpose:type_name -> ckodex.assurance.control.v1.ImplementationPurpose
	1, // 1: ckodex.assurance.control.v1.ImplementationBinding.controls:type_name -> ckodex.assurance.control.v1.ControlRef
	5, // 2: ckodex.assurance.control.v1.ImplementationBinding.subjects:type_name -> ckodex.assurance.common.v1.SubjectRef
	2, // 3: ckodex.assurance.control.v1.ImplementationBinding.implementations:type_name -> ckodex.assurance.control.v1.ImplementationRef
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_assurance_control_v1_control_proto_init() }
func file_assurance_control_v1_control_proto_init() {
	if File_assurance_control_v1_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_assurance_control_v1_control_proto_rawDesc), len(file_assurance_control_v1_control_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_assurance_control_v1_control_proto_goTypes,
		DependencyIndexes: file_assurance_control_v1_control_proto_depIdxs,
		EnumInfos:         file_assurance_control_v1_control_proto_enumTypes,
		MessageInfos:      file_assurance_control_v1_control_proto_msgTypes,
	}.Build()
	File_assurance_control_v1_control_proto = out.File
	file_assurance_control_v1_control_proto_goTypes = nil
	file_assurance_control_v1_control_proto_depIdxs = nil
}
