// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: assurance/receipt/v1/receipt.proto

package receiptv1

import (
	v1 "github.com/ckodex-labs/oskal/proto/assurance/common/v1"
	v11 "github.com/ckodex-labs/oskal/proto/assurance/control/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ControlReceipt is a cryptographically verifiable record of an evaluation.
type ControlReceipt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       *v1.SubjectRef         `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Control       *v11.ControlRef        `protobuf:"bytes,2,opt,name=control,proto3" json:"control,omitempty"`
	State         v1.AssuranceState      `protobuf:"varint,3,opt,name=state,proto3,enum=ckodex.assurance.common.v1.AssuranceState" json:"state,omitempty"`
	Epoch         *v1.AssuranceEpoch     `protobuf:"bytes,4,opt,name=epoch,proto3" json:"epoch,omitempty"`
	EvidenceRoot  string                 `protobuf:"bytes,5,opt,name=evidence_root,json=evidenceRoot,proto3" json:"evidence_root,omitempty"`
	Evaluator     *v1.AuthorityRef       `protobuf:"bytes,6,opt,name=evaluator,proto3" json:"evaluator,omitempty"`
	EvaluatedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=evaluated_at,json=evaluatedAt,proto3" json:"evaluated_at,omitempty"`
	Signature     string                 `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	Format        string                 `protobuf:"bytes,9,opt,name=format,proto3" json:"format,omitempty"` // e.g. "sigstore-bundle", "ed25519"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlReceipt) Reset() {
	*x = ControlReceipt{}
	mi := &file_assurance_receipt_v1_receipt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlReceipt) ProtoMessage() {}

func (x *ControlReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_assurance_receipt_v1_receipt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlReceipt.ProtoReflect.Descriptor instead.
func (*ControlReceipt) Descriptor() ([]byte, []int) {
	return file_assurance_receipt_v1_receipt_proto_rawDescGZIP(), []int{0}
}

func (x *ControlReceipt) GetSubject() *v1.SubjectRef {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *ControlReceipt) GetControl() *v11.ControlRef {
	if x != nil {
		return x.Control
	}
	return nil
}

func (x *ControlReceipt) GetState() v1.AssuranceState {
	if x != nil {
		return x.State
	}
	return v1.AssuranceState(0)
}

func (x *ControlReceipt) GetEpoch() *v1.AssuranceEpoch {
	if x != nil {
		return x.Epoch
	}
	return nil
}

func (x *ControlReceipt) GetEvidenceRoot() string {
	if x != nil {
		return x.EvidenceRoot
	}
	return ""
}

func (x *ControlReceipt) GetEvaluator() *v1.AuthorityRef {
	if x != nil {
		return x.Evaluator
	}
	return nil
}

func (x *ControlReceipt) GetEvaluatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EvaluatedAt
	}
	return nil
}

func (x *ControlReceipt) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *ControlReceipt) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

var File_assurance_receipt_v1_receipt_proto protoreflect.FileDescriptor

const file_assurance_receipt_v1_receipt_proto_rawDesc = "" +
	"\n" +
	"\"assurance/receipt/v1/receipt.proto\x12\x1bckodex.assurance.receipt.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a assurance/common/v1/common.proto\x1a\"assurance/control/v1/control.proto\"\xfb\x03\n" +
	"\x0eControlReceipt\x12@\n" +
	"\asubject\x18\x01 \x01(\v2&.ckodex.assurance.common.v1.SubjectRefR\asubject\x12A\n" +
	"\acontrol\x18\x02 \x01(\v2'.ckodex.assurance.control.v1.ControlRefR\acontrol\x12@\n" +
	"\x05state\x18\x03 \x01(\x0e2*.ckodex.assurance.common.v1.AssuranceStateR\x05state\x12@\n" +
	"\x05epoch\x18\x04 \x01(\v2*.ckodex.assurance.common.v1.AssuranceEpochR\x05epoch\x12#\n" +
	"\revidence_root\x18\x05 \x01(\tR\fevidenceRoot\x12F\n" +
	"\tevaluator\x18\x06 \x01(\v2(.ckodex.assurance.common.v1.AuthorityRefR\tevaluator\x12=\n" +
	"\fevaluated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vevaluatedAt\x12\x1c\n" +
	"\tsignature\x18\b \x01(\tR\tsignature\x12\x16\n" +
	"\x06format\x18\t \x01(\tR\x06formatBCZAgithub.com/ckodex-labs/oskal/proto/assurance/receipt/v1;receiptv1b\x06proto3"

var (
	file_assurance_receipt_v1_receipt_proto_rawDescOnce sync.Once
	file_assurance_receipt_v1_receipt_proto_rawDescData []byte
)

func file_assurance_receipt_v1_receipt_proto_rawDescGZIP() []byte {
	file_assurance_receipt_v1_receipt_proto_rawDescOnce.Do(func() {
		file_assurance_receipt_v1_receipt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_assurance_receipt_v1_receipt_proto_rawDesc), len(file_assurance_receipt_v1_receipt_proto_rawDesc)))
	})
	return file_assurance_receipt_v1_receipt_proto_rawDescData
}

var file_assurance_receipt_v1_receipt_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_assurance_receipt_v1_receipt_proto_goTypes = []any{
	(*ControlReceipt)(nil),        // 0: ckodex.assurance.receipt.v1.ControlReceipt
	(*v1.SubjectRef)(nil),         // 1: ckodex.assurance.common.v1.SubjectRef
	(*v11.ControlRef)(nil),        // 2: ckodex.assurance.control.v1.ControlRef
	(v1.AssuranceState)(0),        // 3: ckodex.assurance.common.v1.AssuranceState
	(*v1.AssuranceEpoch)(nil),     // 4: ckodex.assurance.common.v1.AssuranceEpoch
	(*v1.AuthorityRef)(nil),       // 5: ckodex.assurance.common.v1.AuthorityRef
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_assurance_receipt_v1_receipt_proto_depIdxs = []int32{
	1, // 0: ckodex.assurance.receipt.v1.ControlReceipt.subject:type_name -> ckodex.assurance.common.v1.SubjectRef
	2, // 1: ckodex.assurance.receipt.v1.ControlReceipt.control:type_name -> ckodex.assurance.control.v1.ControlRef
	3, // 2: ckodex.assurance.receipt.v1.ControlReceipt.state:type_name -> ckodex.assurance.common.v1.AssuranceState
	4, // 3: ckodex.assurance.receipt.v1.ControlReceipt.epoch:type_name -> ckodex.assurance.common.v1.AssuranceEpoch
	5, // 4: ckodex.assurance.receipt.v1.ControlReceipt.evaluator:type_name -> ckodex.assurance.common.v1.AuthorityRef
	6, // 5: ckodex.assurance.receipt.v1.ControlReceipt.evaluated_at:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_assurance_receipt_v1_receipt_proto_init() }
func file_assurance_receipt_v1_receipt_proto_init() {
	if File_assurance_receipt_v1_receipt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_assurance_receipt_v1_receipt_proto_rawDesc), len(file_assurance_receipt_v1_receipt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_assurance_receipt_v1_receipt_proto_goTypes,
		DependencyIndexes: file_assurance_receipt_v1_receipt_proto_depIdxs,
		MessageInfos:      file_assurance_receipt_v1_receipt_proto_msgTypes,
	}.Build()
	File_assurance_receipt_v1_receipt_proto = out.File
	file_assurance_receipt_v1_receipt_proto_goTypes = nil
	file_assurance_receipt_v1_receipt_proto_depIdxs = nil
}
